/**
 * airline_reviews.ts — B8 (May 2026)
 *
 * Reviews curados de 12 aerolíneas top con datos públicos:
 * puntualidad (FlightStats agg), comodidad asientos, comida,
 * equipaje, política bag perdido, customer service, value.
 */

export type AirlineReview = {
  iata: string;
  icao: string;
  name: string;
  hub: string;
  alliance: "Star Alliance" | "Oneworld" | "SkyTeam" | "Ninguna";
  star_rating: number; // 1-5
  on_time_pct: number;
  bag_lost_per_1000: number;
  cabin_score: number; // /10
  food_score: number; // /10
  service_score: number; // /10
  value_score: number; // /10
  best_for: string[];
  worst_for: string[];
  hand_baggage_kg: number;
  cabin_baggage_dims: string;
  checked_baggage_included: boolean;
  pros: string[];
  cons: string[];
  verdict: string;
};

export const AIRLINE_REVIEWS: AirlineReview[] = [
  {
    iata: "IB",
    icao: "IBE",
    name: "Iberia",
    hub: "Madrid (MAD)",
    alliance: "Oneworld",
    star_rating: 4,
    on_time_pct: 78,
    bag_lost_per_1000: 5.2,
    cabin_score: 7,
    food_score: 6,
    service_score: 8,
    value_score: 7,
    best_for: ["Latinoamérica", "Conexiones MAD", "Avios"],
    worst_for: ["Long-haul Asia premium", "Equipaje en económica básica"],
    hand_baggage_kg: 10,
    cabin_baggage_dims: "56×40×25 cm",
    checked_baggage_included: false,
    pros: [
      "Mejor red a Latam desde Europa",
      "Avios fáciles de acumular",
      "Servicio en español",
      "Renovación flota A350 para long-haul",
    ],
    cons: [
      "Económica sin equipaje desde 2023",
      "Comida media inferior a competidores",
      "Tarifas baja flexibilidad",
    ],
    verdict: "Sólido para vuelos a Latam y conexiones MAD. Para Europa, low-cost a menudo gana.",
  },
  {
    iata: "FR",
    icao: "RYR",
    name: "Ryanair",
    hub: "Dublín (DUB)",
    alliance: "Ninguna",
    star_rating: 2,
    on_time_pct: 81,
    bag_lost_per_1000: 0.6,
    cabin_score: 4,
    food_score: 2,
    service_score: 4,
    value_score: 9,
    best_for: ["Vuelos Europa baratos", "Solo equipaje pequeño", "Fechas flexibles"],
    worst_for: ["Comodidad", "Servicio al cliente", "Equipaje grande"],
    hand_baggage_kg: 10,
    cabin_baggage_dims: "40×20×25 cm (mochila pequeña gratis)",
    checked_baggage_included: false,
    pros: [
      "Los precios más bajos de Europa",
      "Puntualidad alta",
      "Red densa (rutas únicas)",
      "Bolsa pérdida mínima",
    ],
    cons: [
      "Asientos no reclinables, espacio mínimo",
      "Cobran TODO (asiento, equipaje, prioridad)",
      "Servicio cliente prácticamente inexistente",
      "Aeropuertos secundarios alejados",
    ],
    verdict: "Vuelas tú, no te llevan. Si gestionas el equipaje y aceptas las reglas, imbatible en precio.",
  },
  {
    iata: "VY",
    icao: "VLG",
    name: "Vueling",
    hub: "Barcelona (BCN)",
    alliance: "Ninguna",
    star_rating: 3,
    on_time_pct: 71,
    bag_lost_per_1000: 7.5,
    cabin_score: 5,
    food_score: 4,
    service_score: 5,
    value_score: 7,
    best_for: ["España doméstico", "Europa mid-range", "BCN hub"],
    worst_for: ["Puntualidad", "Servicio si hay incidencia"],
    hand_baggage_kg: 10,
    cabin_baggage_dims: "55×40×20 cm",
    checked_baggage_included: false,
    pros: [
      "Mejor red interna España",
      "Más cómodo que Ryanair",
      "Programa Avios compatible Iberia",
    ],
    cons: [
      "Puntualidad de las peores en EU",
      "Cancelaciones frecuentes",
      "Difícil contactar customer service",
    ],
    verdict: "Aceptable para Europa, problemática si hay incidencia. Compra siempre con flexibilidad.",
  },
  {
    iata: "U2",
    icao: "EZY",
    name: "easyJet",
    hub: "Londres-Luton (LTN)",
    alliance: "Ninguna",
    star_rating: 3,
    on_time_pct: 76,
    bag_lost_per_1000: 1.2,
    cabin_score: 6,
    food_score: 4,
    service_score: 6,
    value_score: 8,
    best_for: ["UK ↔ Europa", "Mid-range low-cost"],
    worst_for: ["Long-haul (no opera)"],
    hand_baggage_kg: 15,
    cabin_baggage_dims: "45×36×20 cm gratis (cabina)",
    checked_baggage_included: false,
    pros: [
      "Más cómodo que Ryanair",
      "App muy buena",
      "Mejor servicio cliente que Ryanair",
      "Aeropuertos principales",
    ],
    cons: [
      "Huelgas frecuentes UK",
      "Cancelaciones verano",
    ],
    verdict: "El low-cost europeo más equilibrado. Mejor que Ryanair para 90%+ rutas.",
  },
  {
    iata: "LH",
    icao: "DLH",
    name: "Lufthansa",
    hub: "Frankfurt + Múnich",
    alliance: "Star Alliance",
    star_rating: 4,
    on_time_pct: 73,
    bag_lost_per_1000: 12.5,
    cabin_score: 8,
    food_score: 7,
    service_score: 8,
    value_score: 5,
    best_for: ["Conexiones Asia/USA via FRA", "Business class"],
    worst_for: ["Equipaje (ratio pérdida alto)", "Precios económica"],
    hand_baggage_kg: 8,
    cabin_baggage_dims: "55×40×23 cm",
    checked_baggage_included: true,
    pros: [
      "Excelente red mundial",
      "Business class top",
      "Asientos cómodos en económica",
      "Comida decente",
    ],
    cons: [
      "Ratio bolsas perdidas alto (FRA hub problemático)",
      "Huelgas frecuentes 2024-25",
      "Económica cara vs competidores",
    ],
    verdict: "Premium de verdad pero con problemas operativos en hubs. Excelente para business.",
  },
  {
    iata: "AF",
    icao: "AFR",
    name: "Air France",
    hub: "París CDG",
    alliance: "SkyTeam",
    star_rating: 4,
    on_time_pct: 72,
    bag_lost_per_1000: 9.8,
    cabin_score: 8,
    food_score: 8,
    service_score: 7,
    value_score: 6,
    best_for: ["Latam vía CDG", "Comida (pan + queso)", "Premium economy"],
    worst_for: ["Customer service en huelga"],
    hand_baggage_kg: 12,
    cabin_baggage_dims: "55×35×25 cm",
    checked_baggage_included: true,
    pros: [
      "Comida de las mejores del mundo (incluso económica)",
      "Asientos cómodos A350/B777",
      "Red Latam fuerte",
      "Premium economy bien valorada",
    ],
    cons: [
      "Huelgas frecuentes",
      "CDG hub puede ser caótico",
    ],
    verdict: "Producto top en cabina, operación poco fiable.",
  },
  {
    iata: "BA",
    icao: "BAW",
    name: "British Airways",
    hub: "Londres Heathrow",
    alliance: "Oneworld",
    star_rating: 4,
    on_time_pct: 70,
    bag_lost_per_1000: 14.2,
    cabin_score: 7,
    food_score: 6,
    service_score: 7,
    value_score: 6,
    best_for: ["LHR conexiones mundo", "Avios (con cuidado fees)"],
    worst_for: ["Económica corta distancia", "Tasas APD UK"],
    hand_baggage_kg: 23,
    cabin_baggage_dims: "56×45×25 cm (1 + 1 personal)",
    checked_baggage_included: true,
    pros: [
      "Hub LHR conecta a casi todo",
      "Cabin baggage generoso (23kg!)",
      "Lounges Avios decentes",
      "Renovación flota A350",
    ],
    cons: [
      "Ratio bolsas perdidas el peor del top 5",
      "Económica corta = cobran agua/snacks",
      "Avios con fuel surcharges altos",
    ],
    verdict: "Servicio decente, operación problemática. Equipaje cabina es ventaja real.",
  },
  {
    iata: "TP",
    icao: "TAP",
    name: "TAP Air Portugal",
    hub: "Lisboa (LIS)",
    alliance: "Star Alliance",
    star_rating: 3,
    on_time_pct: 65,
    bag_lost_per_1000: 18.7,
    cabin_score: 6,
    food_score: 6,
    service_score: 6,
    value_score: 7,
    best_for: ["LIS hub a Brasil/África", "Stopover gratis"],
    worst_for: ["Puntualidad", "Bolsa equipaje"],
    hand_baggage_kg: 8,
    cabin_baggage_dims: "55×40×20 cm",
    checked_baggage_included: false,
    pros: [
      "Stopover Lisboa hasta 5 noches gratis",
      "Conexiones Brasil/África competitivas",
      "Precios atractivos",
    ],
    cons: [
      "Puntualidad de las peores",
      "Ratio pérdida equipaje muy alto",
      "Renovación flota lenta",
    ],
    verdict: "Vale el riesgo si tienes flexibilidad. Stopover gratis es ventaja real.",
  },
  {
    iata: "EK",
    icao: "UAE",
    name: "Emirates",
    hub: "Dubái (DXB)",
    alliance: "Ninguna",
    star_rating: 5,
    on_time_pct: 81,
    bag_lost_per_1000: 3.1,
    cabin_score: 9,
    food_score: 9,
    service_score: 9,
    value_score: 7,
    best_for: ["Asia vía DXB", "Long-haul lujo", "Familia (servicio niños)"],
    worst_for: ["Conexiones cortas Europa"],
    hand_baggage_kg: 7,
    cabin_baggage_dims: "55×38×20 cm",
    checked_baggage_included: true,
    pros: [
      "Producto de cabina top mundial",
      "Comida excelente incluso económica",
      "Servicio niños increíble",
      "Flota A380 + 777 modernísima",
    ],
    cons: [
      "Pueden cobrar selección asiento",
      "DXB hub es enorme (puede ser caótico)",
    ],
    verdict: "Para long-haul Asia/Australia, mejor opción premium-económica.",
  },
  {
    iata: "QR",
    icao: "QTR",
    name: "Qatar Airways",
    hub: "Doha (DOH)",
    alliance: "Oneworld",
    star_rating: 5,
    on_time_pct: 84,
    bag_lost_per_1000: 2.4,
    cabin_score: 9,
    food_score: 9,
    service_score: 9,
    value_score: 8,
    best_for: ["Long-haul Asia/Oceanía", "Q-suite business", "Equipaje cabina"],
    worst_for: ["Vuelos cortos"],
    hand_baggage_kg: 7,
    cabin_baggage_dims: "50×37×25 cm",
    checked_baggage_included: true,
    pros: [
      "Skytrax Airline of the Year múltiples años",
      "Q-suite business class la mejor del mercado",
      "Equipaje cabina hasta 7kg + personal item",
      "Hub DOH compacto y eficiente",
    ],
    cons: [
      "Restricción Qatar Airways Privilege Club ↔ Avios",
      "Pueden cobrar selección asiento en económica",
    ],
    verdict: "Mejor aerolínea Skytrax. Para long-haul Asia es sin duda la opción top.",
  },
  {
    iata: "TK",
    icao: "THY",
    name: "Turkish Airlines",
    hub: "Estambul (IST)",
    alliance: "Star Alliance",
    star_rating: 4,
    on_time_pct: 78,
    bag_lost_per_1000: 5.8,
    cabin_score: 8,
    food_score: 9,
    service_score: 8,
    value_score: 8,
    best_for: ["Asia/África vía IST", "Comida (la mejor en económica)", "Stopover Estambul gratis"],
    worst_for: ["IST aeropuerto enorme = conexiones largas"],
    hand_baggage_kg: 8,
    cabin_baggage_dims: "55×40×23 cm",
    checked_baggage_included: true,
    pros: [
      "Comida en económica = mejor del mundo",
      "Hub IST conecta a TODO",
      "Stopover Estambul 1-2 días gratis",
      "Equipaje generoso 30kg en Asia",
    ],
    cons: [
      "Aeropuerto IST enorme (puede ser caos)",
      "Conexiones a veces 4-6h",
    ],
    verdict: "Sleeper option excelente para Asia. Comida sola vale el viaje.",
  },
  {
    iata: "JL",
    icao: "JAL",
    name: "JAL (Japan Airlines)",
    hub: "Tokio Haneda + Narita",
    alliance: "Oneworld",
    star_rating: 5,
    on_time_pct: 91,
    bag_lost_per_1000: 0.4,
    cabin_score: 9,
    food_score: 9,
    service_score: 10,
    value_score: 8,
    best_for: ["Vuelos a Japón", "Servicio omotenashi", "Puntualidad extrema"],
    worst_for: ["Precios premium"],
    hand_baggage_kg: 10,
    cabin_baggage_dims: "55×40×25 cm",
    checked_baggage_included: true,
    pros: [
      "Puntualidad japonesa (91% on-time)",
      "Casi nunca pierden bolsas (0.4‰)",
      "Servicio omotenashi inigualable",
      "Comida japonesa real incluso económica",
    ],
    cons: [
      "Precios más altos que conexiones via Asia",
      "Pocas rutas directas desde España",
    ],
    verdict: "Si vas a Japón directo, vale la diferencia. Mejor servicio del mundo.",
  },
];

export function getAirlineReview(iata: string): AirlineReview | undefined {
  return AIRLINE_REVIEWS.find((a) => a.iata === iata.toUpperCase());
}
