/**
 * airports.ts — catálogo estático de aeropuertos para el autocomplete.
 *
 * Cada entrada incluye:
 *  - iata: código IATA de 3 letras (único).
 *  - city: nombre localizado para UI en español.
 *  - country: país (etiqueta corta, en español).
 *  - alt: nombres alternativos para matching (inglés, idioma local, sinónimos
 *    comunes). Una búsqueda como "new york", "münchen", "lisbon" debe
 *    resolver al IATA correcto aunque el nombre mostrado sea otro.
 *
 * Si necesitas cambiar el orden de prioridad en el dropdown: los primeros
 * aeropuertos (hubs DACH + España) se muestran cuando la query está vacía.
 * Todo lo demás compite por substring match.
 *
 * Mantenemos este listado en el frontend para que el autocomplete funcione
 * sin red (primer render instantáneo) y sobreviva si `/api/airports` está
 * caído. El backend tiene un catálogo más amplio para enriquecer deals,
 * pero el usuario típico sólo necesita ~200 ciudades relevantes.
 */

export interface AirportEntry {
  iata: string;
  city: string;
  country: string;
  /** Nombres alternativos para búsqueda — nunca se muestran en UI. */
  alt?: string[];
}

export const TOP_AIRPORTS: AirportEntry[] = [
  // ── DACH hubs (audiencia principal) ──
  { iata: "BSL", city: "Basilea/Mulhouse", country: "Suiza/Francia", alt: ["basel", "euroairport", "mulhouse"] },
  { iata: "ZRH", city: "Zúrich", country: "Suiza", alt: ["zurich", "zürich", "kloten"] },
  { iata: "GVA", city: "Ginebra", country: "Suiza", alt: ["geneva", "genève", "genf"] },
  { iata: "BRN", city: "Berna", country: "Suiza", alt: ["bern"] },
  { iata: "LUG", city: "Lugano", country: "Suiza" },
  { iata: "FRA", city: "Fráncfort", country: "Alemania", alt: ["frankfurt", "frankfurt am main"] },
  { iata: "MUC", city: "Múnich", country: "Alemania", alt: ["munich", "münchen", "franz josef strauss"] },
  { iata: "BER", city: "Berlín", country: "Alemania", alt: ["berlin", "brandenburg", "tegel", "schönefeld"] },
  { iata: "HAM", city: "Hamburgo", country: "Alemania", alt: ["hamburg"] },
  { iata: "DUS", city: "Düsseldorf", country: "Alemania", alt: ["dusseldorf", "duesseldorf"] },
  { iata: "STR", city: "Stuttgart", country: "Alemania" },
  { iata: "CGN", city: "Colonia", country: "Alemania", alt: ["cologne", "köln", "koeln", "bonn"] },
  { iata: "NUE", city: "Núremberg", country: "Alemania", alt: ["nuremberg", "nürnberg", "nuernberg"] },
  { iata: "LEJ", city: "Leipzig", country: "Alemania" },
  { iata: "HAJ", city: "Hannover", country: "Alemania", alt: ["hanover"] },
  { iata: "BRE", city: "Bremen", country: "Alemania" },
  { iata: "VIE", city: "Viena", country: "Austria", alt: ["vienna", "wien"] },
  { iata: "SZG", city: "Salzburgo", country: "Austria", alt: ["salzburg"] },
  { iata: "INN", city: "Innsbruck", country: "Austria" },
  { iata: "GRZ", city: "Graz", country: "Austria" },

  // ── España ──
  { iata: "MAD", city: "Madrid", country: "España", alt: ["madrid", "barajas"] },
  { iata: "BCN", city: "Barcelona", country: "España", alt: ["barcelona", "el prat"] },
  { iata: "AGP", city: "Málaga", country: "España", alt: ["malaga", "costa del sol"] },
  { iata: "VLC", city: "Valencia", country: "España" },
  { iata: "SVQ", city: "Sevilla", country: "España", alt: ["seville", "sevilla"] },
  { iata: "BIO", city: "Bilbao", country: "España" },
  { iata: "PMI", city: "Palma de Mallorca", country: "España", alt: ["palma", "mallorca", "majorca"] },
  { iata: "IBZ", city: "Ibiza", country: "España" },
  { iata: "MAH", city: "Menorca", country: "España", alt: ["mahon", "mahón", "minorca"] },
  { iata: "TFS", city: "Tenerife Sur", country: "España", alt: ["tenerife south", "reina sofia"] },
  { iata: "TFN", city: "Tenerife Norte", country: "España", alt: ["tenerife north", "los rodeos"] },
  { iata: "LPA", city: "Gran Canaria", country: "España", alt: ["las palmas", "canary islands"] },
  { iata: "ACE", city: "Lanzarote", country: "España", alt: ["arrecife"] },
  { iata: "FUE", city: "Fuerteventura", country: "España" },
  { iata: "ALC", city: "Alicante", country: "España", alt: ["alacant", "alicante-elche"] },
  { iata: "SDR", city: "Santander", country: "España" },
  { iata: "SCQ", city: "Santiago de Compostela", country: "España", alt: ["santiago compostela"] },
  { iata: "VGO", city: "Vigo", country: "España" },
  { iata: "GRO", city: "Girona", country: "España", alt: ["gerona", "costa brava"] },
  { iata: "REU", city: "Reus", country: "España", alt: ["tarragona"] },
  { iata: "ZAZ", city: "Zaragoza", country: "España", alt: ["saragossa"] },
  { iata: "XRY", city: "Jerez", country: "España", alt: ["jerez de la frontera"] },
  { iata: "MLN", city: "Melilla", country: "España" },

  // ── Portugal ──
  { iata: "LIS", city: "Lisboa", country: "Portugal", alt: ["lisbon", "lissabon", "portela"] },
  { iata: "OPO", city: "Oporto", country: "Portugal", alt: ["porto", "oporto"] },
  { iata: "FAO", city: "Faro", country: "Portugal", alt: ["algarve"] },
  { iata: "FNC", city: "Funchal", country: "Portugal", alt: ["madeira", "madera"] },
  { iata: "PDL", city: "Ponta Delgada", country: "Portugal", alt: ["azores", "azoren"] },

  // ── Francia ──
  { iata: "CDG", city: "París CDG", country: "Francia", alt: ["paris", "charles de gaulle", "roissy"] },
  { iata: "ORY", city: "París Orly", country: "Francia", alt: ["paris orly", "orly"] },
  { iata: "BVA", city: "París Beauvais", country: "Francia", alt: ["paris beauvais", "beauvais"] },
  { iata: "LYS", city: "Lyon", country: "Francia", alt: ["lyon saint exupery"] },
  { iata: "MRS", city: "Marsella", country: "Francia", alt: ["marseille"] },
  { iata: "NCE", city: "Niza", country: "Francia", alt: ["nice", "cote d'azur"] },
  { iata: "TLS", city: "Toulouse", country: "Francia", alt: ["tolosa"] },
  { iata: "BOD", city: "Burdeos", country: "Francia", alt: ["bordeaux"] },
  { iata: "NTE", city: "Nantes", country: "Francia" },
  { iata: "BIQ", city: "Biarritz", country: "Francia" },
  { iata: "SXB", city: "Estrasburgo", country: "Francia", alt: ["strasbourg", "strasburg"] },

  // ── Reino Unido + Irlanda ──
  { iata: "LHR", city: "Londres Heathrow", country: "Reino Unido", alt: ["london heathrow", "london", "londres"] },
  { iata: "LGW", city: "Londres Gatwick", country: "Reino Unido", alt: ["london gatwick", "london", "londres"] },
  { iata: "STN", city: "Londres Stansted", country: "Reino Unido", alt: ["london stansted", "london", "londres"] },
  { iata: "LTN", city: "Londres Luton", country: "Reino Unido", alt: ["london luton", "london", "londres"] },
  { iata: "LCY", city: "Londres City", country: "Reino Unido", alt: ["london city", "london", "londres"] },
  { iata: "MAN", city: "Mánchester", country: "Reino Unido", alt: ["manchester"] },
  { iata: "EDI", city: "Edimburgo", country: "Reino Unido", alt: ["edinburgh"] },
  { iata: "GLA", city: "Glasgow", country: "Reino Unido" },
  { iata: "BHX", city: "Birmingham", country: "Reino Unido" },
  { iata: "BRS", city: "Bristol", country: "Reino Unido" },
  { iata: "NCL", city: "Newcastle", country: "Reino Unido" },
  { iata: "LPL", city: "Liverpool", country: "Reino Unido" },
  { iata: "DUB", city: "Dublín", country: "Irlanda", alt: ["dublin"] },
  { iata: "ORK", city: "Cork", country: "Irlanda" },
  { iata: "SNN", city: "Shannon", country: "Irlanda" },

  // ── Italia ──
  { iata: "FCO", city: "Roma", country: "Italia", alt: ["rome", "rom", "fiumicino", "leonardo da vinci"] },
  { iata: "CIA", city: "Roma Ciampino", country: "Italia", alt: ["rome ciampino", "ciampino"] },
  { iata: "MXP", city: "Milán Malpensa", country: "Italia", alt: ["milan", "milano", "malpensa", "mailand"] },
  { iata: "LIN", city: "Milán Linate", country: "Italia", alt: ["milan linate", "milano linate"] },
  { iata: "BGY", city: "Bérgamo", country: "Italia", alt: ["bergamo", "milan bergamo", "orio al serio"] },
  { iata: "VCE", city: "Venecia", country: "Italia", alt: ["venice", "venedig", "venezia", "marco polo"] },
  { iata: "TSF", city: "Venecia Treviso", country: "Italia", alt: ["venice treviso", "treviso"] },
  { iata: "NAP", city: "Nápoles", country: "Italia", alt: ["naples", "napoli"] },
  { iata: "PMO", city: "Palermo", country: "Italia" },
  { iata: "CTA", city: "Catania", country: "Italia", alt: ["sicily", "sicilia"] },
  { iata: "BLQ", city: "Bolonia", country: "Italia", alt: ["bologna"] },
  { iata: "FLR", city: "Florencia", country: "Italia", alt: ["florence", "firenze"] },
  { iata: "PSA", city: "Pisa", country: "Italia" },
  { iata: "TRN", city: "Turín", country: "Italia", alt: ["turin", "torino"] },
  { iata: "BRI", city: "Bari", country: "Italia" },
  { iata: "CAG", city: "Cagliari", country: "Italia", alt: ["sardinia", "cerdeña"] },

  // ── Países Bajos / Bélgica / Luxemburgo ──
  { iata: "AMS", city: "Ámsterdam", country: "Países Bajos", alt: ["amsterdam", "schiphol", "holland", "holanda"] },
  { iata: "EIN", city: "Eindhoven", country: "Países Bajos" },
  { iata: "RTM", city: "Róterdam", country: "Países Bajos", alt: ["rotterdam"] },
  { iata: "BRU", city: "Bruselas", country: "Bélgica", alt: ["brussels", "brussel", "bruxelles"] },
  { iata: "CRL", city: "Charleroi", country: "Bélgica", alt: ["brussels south", "bruselas sur"] },
  { iata: "ANR", city: "Amberes", country: "Bélgica", alt: ["antwerp", "antwerpen"] },
  { iata: "LUX", city: "Luxemburgo", country: "Luxemburgo", alt: ["luxembourg", "findel"] },

  // ── Europa del Norte ──
  { iata: "CPH", city: "Copenhague", country: "Dinamarca", alt: ["copenhagen", "kopenhagen", "københavn"] },
  { iata: "ARN", city: "Estocolmo", country: "Suecia", alt: ["stockholm", "arlanda"] },
  { iata: "GOT", city: "Gotemburgo", country: "Suecia", alt: ["gothenburg", "göteborg"] },
  { iata: "OSL", city: "Oslo", country: "Noruega", alt: ["gardermoen"] },
  { iata: "BGO", city: "Bergen", country: "Noruega" },
  { iata: "TRD", city: "Trondheim", country: "Noruega" },
  { iata: "HEL", city: "Helsinki", country: "Finlandia", alt: ["vantaa"] },
  { iata: "KEF", city: "Reikiavik", country: "Islandia", alt: ["reykjavik", "keflavik"] },

  // ── Europa del Este / Central ──
  { iata: "PRG", city: "Praga", country: "Chequia", alt: ["prague", "prag", "praha"] },
  { iata: "WAW", city: "Varsovia", country: "Polonia", alt: ["warsaw", "warszawa", "chopin"] },
  { iata: "KRK", city: "Cracovia", country: "Polonia", alt: ["krakow", "cracow"] },
  { iata: "GDN", city: "Gdansk", country: "Polonia", alt: ["gdańsk"] },
  { iata: "BUD", city: "Budapest", country: "Hungría", alt: ["ferenc liszt"] },
  { iata: "OTP", city: "Bucarest", country: "Rumanía", alt: ["bucharest", "henri coanda"] },
  { iata: "SOF", city: "Sofía", country: "Bulgaria", alt: ["sofia"] },
  { iata: "BEG", city: "Belgrado", country: "Serbia", alt: ["belgrade", "beograd", "nikola tesla"] },
  { iata: "ZAG", city: "Zagreb", country: "Croacia" },
  { iata: "SPU", city: "Split", country: "Croacia", alt: ["dalmatia", "dalmacia"] },
  { iata: "DBV", city: "Dubrovnik", country: "Croacia" },
  { iata: "LJU", city: "Liubliana", country: "Eslovenia", alt: ["ljubljana", "laibach"] },
  { iata: "TLL", city: "Tallin", country: "Estonia", alt: ["tallinn"] },
  { iata: "RIX", city: "Riga", country: "Letonia" },
  { iata: "VNO", city: "Vilna", country: "Lituania", alt: ["vilnius"] },
  { iata: "KBP", city: "Kiev", country: "Ucrania", alt: ["kyiv", "boryspil"] },

  // ── Grecia / Chipre / Turquía / Malta ──
  { iata: "ATH", city: "Atenas", country: "Grecia", alt: ["athens", "athina"] },
  { iata: "SKG", city: "Tesalónica", country: "Grecia", alt: ["thessaloniki", "salonica"] },
  { iata: "HER", city: "Heraclión", country: "Grecia", alt: ["heraklion", "crete", "creta"] },
  { iata: "RHO", city: "Rodas", country: "Grecia", alt: ["rhodes"] },
  { iata: "JMK", city: "Míkonos", country: "Grecia", alt: ["mykonos"] },
  { iata: "JTR", city: "Santorini", country: "Grecia", alt: ["thira"] },
  { iata: "CFU", city: "Corfú", country: "Grecia", alt: ["corfu", "kerkyra"] },
  { iata: "LCA", city: "Larnaca", country: "Chipre", alt: ["cyprus", "chipre"] },
  { iata: "PFO", city: "Pafos", country: "Chipre", alt: ["paphos"] },
  { iata: "IST", city: "Estambul", country: "Turquía", alt: ["istanbul", "constantinople"] },
  { iata: "SAW", city: "Estambul Sabiha", country: "Turquía", alt: ["istanbul sabiha", "sabiha gokcen"] },
  { iata: "AYT", city: "Antalya", country: "Turquía" },
  { iata: "ESB", city: "Ankara", country: "Turquía" },
  { iata: "MLA", city: "Malta", country: "Malta", alt: ["valletta"] },

  // ── América del Norte ──
  { iata: "JFK", city: "Nueva York JFK", country: "EE.UU.", alt: ["new york", "new york city", "nyc", "kennedy", "nueva york"] },
  { iata: "EWR", city: "Nueva York EWR", country: "EE.UU.", alt: ["new york", "newark", "nueva york", "nyc"] },
  { iata: "LGA", city: "Nueva York LGA", country: "EE.UU.", alt: ["new york", "laguardia", "nueva york", "nyc"] },
  { iata: "LAX", city: "Los Ángeles", country: "EE.UU.", alt: ["los angeles", "la"] },
  { iata: "SFO", city: "San Francisco", country: "EE.UU.", alt: ["sfo"] },
  { iata: "SJC", city: "San José (California)", country: "EE.UU.", alt: ["san jose", "silicon valley"] },
  { iata: "SEA", city: "Seattle", country: "EE.UU.", alt: ["tacoma"] },
  { iata: "PDX", city: "Portland", country: "EE.UU." },
  { iata: "ORD", city: "Chicago O'Hare", country: "EE.UU.", alt: ["chicago", "ohare", "o'hare"] },
  { iata: "MDW", city: "Chicago Midway", country: "EE.UU.", alt: ["chicago", "midway"] },
  { iata: "ATL", city: "Atlanta", country: "EE.UU.", alt: ["hartsfield"] },
  { iata: "MIA", city: "Miami", country: "EE.UU." },
  { iata: "FLL", city: "Fort Lauderdale", country: "EE.UU.", alt: ["miami"] },
  { iata: "MCO", city: "Orlando", country: "EE.UU.", alt: ["disney", "florida"] },
  { iata: "TPA", city: "Tampa", country: "EE.UU." },
  { iata: "BOS", city: "Boston", country: "EE.UU.", alt: ["logan"] },
  { iata: "IAD", city: "Washington Dulles", country: "EE.UU.", alt: ["washington", "dc"] },
  { iata: "DCA", city: "Washington National", country: "EE.UU.", alt: ["washington", "reagan", "dc"] },
  { iata: "PHL", city: "Filadelfia", country: "EE.UU.", alt: ["philadelphia"] },
  { iata: "DFW", city: "Dallas", country: "EE.UU.", alt: ["fort worth"] },
  { iata: "IAH", city: "Houston", country: "EE.UU.", alt: ["bush intercontinental"] },
  { iata: "DEN", city: "Denver", country: "EE.UU." },
  { iata: "LAS", city: "Las Vegas", country: "EE.UU.", alt: ["vegas", "mccarran", "harry reid"] },
  { iata: "PHX", city: "Phoenix", country: "EE.UU.", alt: ["arizona"] },
  { iata: "SAN", city: "San Diego", country: "EE.UU." },
  { iata: "HNL", city: "Honolulu", country: "EE.UU.", alt: ["hawaii", "hawái", "oahu"] },
  { iata: "YYZ", city: "Toronto", country: "Canadá", alt: ["pearson"] },
  { iata: "YUL", city: "Montreal", country: "Canadá", alt: ["trudeau"] },
  { iata: "YVR", city: "Vancouver", country: "Canadá" },
  { iata: "YYC", city: "Calgary", country: "Canadá" },
  { iata: "YOW", city: "Ottawa", country: "Canadá" },
  { iata: "YHZ", city: "Halifax", country: "Canadá" },

  // ── México / Caribe / Centroamérica ──
  { iata: "MEX", city: "Ciudad de México", country: "México", alt: ["mexico city", "mexico df", "mex"] },
  { iata: "CUN", city: "Cancún", country: "México", alt: ["cancun", "riviera maya"] },
  { iata: "GDL", city: "Guadalajara", country: "México" },
  { iata: "MTY", city: "Monterrey", country: "México" },
  { iata: "PVR", city: "Puerto Vallarta", country: "México" },
  { iata: "SJD", city: "Los Cabos", country: "México", alt: ["san jose del cabo", "cabo"] },
  { iata: "HAV", city: "La Habana", country: "Cuba", alt: ["havana", "habana"] },
  { iata: "VRA", city: "Varadero", country: "Cuba" },
  { iata: "SDQ", city: "Santo Domingo", country: "Rep. Dominicana", alt: ["dominican republic", "dominicana"] },
  { iata: "PUJ", city: "Punta Cana", country: "Rep. Dominicana", alt: ["bavaro"] },
  { iata: "SJU", city: "San Juan", country: "Puerto Rico", alt: ["puerto rico"] },
  { iata: "NAS", city: "Nasáu", country: "Bahamas", alt: ["nassau", "bahamas"] },
  { iata: "KIN", city: "Kingston", country: "Jamaica" },
  { iata: "MBJ", city: "Montego Bay", country: "Jamaica" },
  { iata: "SJO", city: "San José (Costa Rica)", country: "Costa Rica" },
  { iata: "LIR", city: "Liberia (Costa Rica)", country: "Costa Rica", alt: ["guanacaste"] },
  { iata: "PTY", city: "Ciudad de Panamá", country: "Panamá", alt: ["panama city", "tocumen"] },

  // ── América del Sur ──
  { iata: "GRU", city: "São Paulo", country: "Brasil", alt: ["sao paulo", "guarulhos"] },
  { iata: "GIG", city: "Río de Janeiro", country: "Brasil", alt: ["rio de janeiro", "galeão", "rio"] },
  { iata: "BSB", city: "Brasilia", country: "Brasil", alt: ["brasília"] },
  { iata: "SSA", city: "Salvador de Bahía", country: "Brasil", alt: ["salvador", "bahia"] },
  { iata: "FOR", city: "Fortaleza", country: "Brasil" },
  { iata: "REC", city: "Recife", country: "Brasil" },
  { iata: "MAO", city: "Manaos", country: "Brasil", alt: ["manaus", "amazon"] },
  { iata: "EZE", city: "Buenos Aires", country: "Argentina", alt: ["ezeiza"] },
  { iata: "AEP", city: "Buenos Aires Aeroparque", country: "Argentina", alt: ["aeroparque", "jorge newbery"] },
  { iata: "COR", city: "Córdoba (Argentina)", country: "Argentina" },
  { iata: "MDZ", city: "Mendoza", country: "Argentina" },
  { iata: "USH", city: "Ushuaia", country: "Argentina", alt: ["tierra del fuego"] },
  { iata: "SCL", city: "Santiago de Chile", country: "Chile", alt: ["santiago", "chile"] },
  { iata: "IPC", city: "Isla de Pascua", country: "Chile", alt: ["easter island", "rapa nui"] },
  { iata: "LIM", city: "Lima", country: "Perú", alt: ["jorge chavez"] },
  { iata: "CUZ", city: "Cusco", country: "Perú", alt: ["cuzco", "machu picchu"] },
  { iata: "BOG", city: "Bogotá", country: "Colombia", alt: ["bogota", "el dorado"] },
  { iata: "MDE", city: "Medellín", country: "Colombia", alt: ["medellin", "jose maria cordova"] },
  { iata: "CTG", city: "Cartagena", country: "Colombia" },
  { iata: "UIO", city: "Quito", country: "Ecuador" },
  { iata: "GYE", city: "Guayaquil", country: "Ecuador" },
  { iata: "GPS", city: "Galápagos", country: "Ecuador", alt: ["galapagos", "baltra"] },
  { iata: "CCS", city: "Caracas", country: "Venezuela", alt: ["maiquetia"] },
  { iata: "MVD", city: "Montevideo", country: "Uruguay" },
  { iata: "ASU", city: "Asunción", country: "Paraguay", alt: ["asuncion"] },
  { iata: "VVI", city: "Santa Cruz", country: "Bolivia" },
  { iata: "LPB", city: "La Paz", country: "Bolivia" },

  // ── Oriente Medio ──
  { iata: "DXB", city: "Dubái", country: "EAU", alt: ["dubai", "emirates"] },
  { iata: "AUH", city: "Abu Dabi", country: "EAU", alt: ["abu dhabi"] },
  { iata: "DOH", city: "Doha", country: "Qatar", alt: ["hamad", "qatar"] },
  { iata: "KWI", city: "Kuwait", country: "Kuwait" },
  { iata: "BAH", city: "Baréin", country: "Baréin", alt: ["bahrain"] },
  { iata: "MCT", city: "Mascate", country: "Omán", alt: ["muscat", "oman"] },
  { iata: "RUH", city: "Riad", country: "Arabia Saudí", alt: ["riyadh", "king khalid"] },
  { iata: "JED", city: "Yeda", country: "Arabia Saudí", alt: ["jeddah", "mecca"] },
  { iata: "TLV", city: "Tel Aviv", country: "Israel", alt: ["ben gurion"] },
  { iata: "AMM", city: "Amán", country: "Jordania", alt: ["amman", "queen alia"] },
  { iata: "BEY", city: "Beirut", country: "Líbano" },

  // ── Asia ──
  { iata: "BKK", city: "Bangkok", country: "Tailandia", alt: ["suvarnabhumi"] },
  { iata: "DMK", city: "Bangkok Don Mueang", country: "Tailandia", alt: ["bangkok don mueang", "dmk"] },
  { iata: "HKT", city: "Phuket", country: "Tailandia" },
  { iata: "CNX", city: "Chiang Mai", country: "Tailandia" },
  { iata: "USM", city: "Koh Samui", country: "Tailandia", alt: ["ko samui"] },
  { iata: "KBV", city: "Krabi", country: "Tailandia" },
  { iata: "SIN", city: "Singapur", country: "Singapur", alt: ["singapore", "changi"] },
  { iata: "KUL", city: "Kuala Lumpur", country: "Malasia", alt: ["malaysia"] },
  { iata: "PEN", city: "Penang", country: "Malasia" },
  { iata: "BKI", city: "Kota Kinabalu", country: "Malasia", alt: ["borneo"] },
  { iata: "CGK", city: "Yakarta", country: "Indonesia", alt: ["jakarta", "soekarno hatta"] },
  { iata: "DPS", city: "Bali", country: "Indonesia", alt: ["denpasar", "ngurah rai"] },
  { iata: "LOP", city: "Lombok", country: "Indonesia" },
  { iata: "MNL", city: "Manila", country: "Filipinas", alt: ["philippines"] },
  { iata: "CEB", city: "Cebú", country: "Filipinas", alt: ["cebu"] },
  { iata: "HKG", city: "Hong Kong", country: "China", alt: ["hongkong"] },
  { iata: "MFM", city: "Macao", country: "China", alt: ["macau"] },
  { iata: "PEK", city: "Pekín Capital", country: "China", alt: ["beijing", "beijing capital"] },
  { iata: "PKX", city: "Pekín Daxing", country: "China", alt: ["beijing daxing", "daxing"] },
  { iata: "PVG", city: "Shanghái Pudong", country: "China", alt: ["shanghai", "pudong"] },
  { iata: "SHA", city: "Shanghái Hongqiao", country: "China", alt: ["shanghai hongqiao", "hongqiao"] },
  { iata: "CAN", city: "Cantón", country: "China", alt: ["guangzhou", "canton"] },
  { iata: "SZX", city: "Shenzhen", country: "China" },
  { iata: "CTU", city: "Chengdu", country: "China" },
  { iata: "NRT", city: "Tokio Narita", country: "Japón", alt: ["tokyo", "narita", "tokio"] },
  { iata: "HND", city: "Tokio Haneda", country: "Japón", alt: ["tokyo haneda", "haneda", "tokio"] },
  { iata: "KIX", city: "Osaka Kansai", country: "Japón", alt: ["kansai", "osaka"] },
  { iata: "ITM", city: "Osaka Itami", country: "Japón", alt: ["osaka itami", "itami"] },
  { iata: "NGO", city: "Nagoya", country: "Japón", alt: ["chubu centrair"] },
  { iata: "FUK", city: "Fukuoka", country: "Japón" },
  { iata: "CTS", city: "Sapporo", country: "Japón", alt: ["new chitose", "hokkaido"] },
  { iata: "OKA", city: "Okinawa", country: "Japón", alt: ["naha"] },
  { iata: "ICN", city: "Seúl Incheon", country: "Corea del Sur", alt: ["seoul", "incheon", "korea"] },
  { iata: "GMP", city: "Seúl Gimpo", country: "Corea del Sur", alt: ["seoul gimpo", "gimpo"] },
  { iata: "TPE", city: "Taipéi", country: "Taiwán", alt: ["taipei", "taoyuan", "taiwan"] },
  { iata: "DEL", city: "Delhi", country: "India", alt: ["new delhi", "nueva delhi", "indira gandhi"] },
  { iata: "BOM", city: "Bombay", country: "India", alt: ["mumbai", "chhatrapati shivaji"] },
  { iata: "BLR", city: "Bangalore", country: "India", alt: ["bengaluru"] },
  { iata: "MAA", city: "Chennai", country: "India", alt: ["madras"] },
  { iata: "CCU", city: "Calcuta", country: "India", alt: ["kolkata", "calcutta"] },
  { iata: "GOI", city: "Goa", country: "India" },
  { iata: "CMB", city: "Colombo", country: "Sri Lanka" },
  { iata: "MLE", city: "Malé", country: "Maldivas", alt: ["male", "maldives"] },
  { iata: "KTM", city: "Katmandú", country: "Nepal", alt: ["kathmandu"] },
  { iata: "SGN", city: "Ho Chi Minh", country: "Vietnam", alt: ["saigon", "tan son nhat"] },
  { iata: "HAN", city: "Hanói", country: "Vietnam", alt: ["hanoi", "noi bai"] },
  { iata: "PNH", city: "Nom Pen", country: "Camboya", alt: ["phnom penh"] },
  { iata: "REP", city: "Siem Reap", country: "Camboya", alt: ["angkor wat"] },
  { iata: "RGN", city: "Rangún", country: "Birmania", alt: ["yangon", "myanmar"] },
  { iata: "ALA", city: "Almatý", country: "Kazajistán", alt: ["almaty"] },
  { iata: "TAS", city: "Taskent", country: "Uzbekistán", alt: ["tashkent"] },

  // ── África ──
  { iata: "CMN", city: "Casablanca", country: "Marruecos", alt: ["mohammed v"] },
  { iata: "RAK", city: "Marrakech", country: "Marruecos", alt: ["marrakesh"] },
  { iata: "AGA", city: "Agadir", country: "Marruecos" },
  { iata: "FEZ", city: "Fez", country: "Marruecos" },
  { iata: "TNG", city: "Tánger", country: "Marruecos", alt: ["tangier", "tangiers"] },
  { iata: "RBA", city: "Rabat", country: "Marruecos" },
  { iata: "CAI", city: "El Cairo", country: "Egipto", alt: ["cairo"] },
  { iata: "HRG", city: "Hurgada", country: "Egipto", alt: ["hurghada"] },
  { iata: "SSH", city: "Sharm el-Sheij", country: "Egipto", alt: ["sharm el sheikh"] },
  { iata: "TUN", city: "Túnez", country: "Túnez", alt: ["tunis", "carthage"] },
  { iata: "DJE", city: "Yerba", country: "Túnez", alt: ["djerba"] },
  { iata: "ALG", city: "Argel", country: "Argelia", alt: ["algiers"] },
  { iata: "NBO", city: "Nairobi", country: "Kenia", alt: ["jomo kenyatta", "kenya"] },
  { iata: "MBA", city: "Mombasa", country: "Kenia" },
  { iata: "ZNZ", city: "Zanzíbar", country: "Tanzania", alt: ["zanzibar"] },
  { iata: "DAR", city: "Dar es Salam", country: "Tanzania", alt: ["dar es salaam"] },
  { iata: "JRO", city: "Kilimanjaro", country: "Tanzania", alt: ["arusha"] },
  { iata: "ADD", city: "Adís Abeba", country: "Etiopía", alt: ["addis ababa"] },
  { iata: "JNB", city: "Johannesburgo", country: "Sudáfrica", alt: ["johannesburg", "joburg", "oliver tambo"] },
  { iata: "CPT", city: "Ciudad del Cabo", country: "Sudáfrica", alt: ["cape town", "kapstadt"] },
  { iata: "DUR", city: "Durban", country: "Sudáfrica" },
  { iata: "WDH", city: "Windhoek", country: "Namibia" },
  { iata: "LOS", city: "Lagos", country: "Nigeria" },
  { iata: "ACC", city: "Acra", country: "Ghana", alt: ["accra"] },
  { iata: "DKR", city: "Dakar", country: "Senegal", alt: ["blaise diagne"] },
  { iata: "SEZ", city: "Seychelles", country: "Seychelles", alt: ["mahe"] },
  { iata: "MRU", city: "Mauricio", country: "Mauricio", alt: ["mauritius"] },
  { iata: "TNR", city: "Antananarivo", country: "Madagascar", alt: ["tana"] },

  // ── Oceanía ──
  { iata: "SYD", city: "Sídney", country: "Australia", alt: ["sydney"] },
  { iata: "MEL", city: "Melbourne", country: "Australia", alt: ["tullamarine"] },
  { iata: "BNE", city: "Brisbane", country: "Australia" },
  { iata: "PER", city: "Perth", country: "Australia" },
  { iata: "ADL", city: "Adelaida", country: "Australia", alt: ["adelaide"] },
  { iata: "CNS", city: "Cairns", country: "Australia", alt: ["great barrier reef"] },
  { iata: "AKL", city: "Auckland", country: "Nueva Zelanda", alt: ["new zealand"] },
  { iata: "WLG", city: "Wellington", country: "Nueva Zelanda" },
  { iata: "CHC", city: "Christchurch", country: "Nueva Zelanda" },
  { iata: "NAN", city: "Nadi", country: "Fiyi", alt: ["fiji"] },
  { iata: "PPT", city: "Papeete", country: "Polinesia Francesa", alt: ["tahiti"] },
  { iata: "HBA", city: "Hobart", country: "Australia", alt: ["tasmania"] },
  { iata: "LST", city: "Launceston", country: "Australia" },
  { iata: "OOL", city: "Gold Coast", country: "Australia", alt: ["coolangatta"] },
  { iata: "MCY", city: "Sunshine Coast", country: "Australia", alt: ["maroochydore"] },

  // ── Islas griegas + Balcanes (ampliación) ──
  { iata: "ZTH", city: "Zante", country: "Grecia", alt: ["zakynthos"] },
  { iata: "KGS", city: "Kos", country: "Grecia" },
  { iata: "SMI", city: "Samos", country: "Grecia" },
  { iata: "MJT", city: "Mitilene", country: "Grecia", alt: ["lesbos", "lesvos", "mytilene"] },
  { iata: "PVK", city: "Preveza", country: "Grecia", alt: ["lefkada"] },
  { iata: "CHQ", city: "La Canea", country: "Grecia", alt: ["chania", "creta", "crete"] },
  { iata: "VAR", city: "Varna", country: "Bulgaria", alt: ["varna black sea"] },
  { iata: "BOJ", city: "Burgas", country: "Bulgaria" },
  { iata: "PRN", city: "Pristina", country: "Kosovo", alt: ["prishtina"] },
  { iata: "TGD", city: "Podgorica", country: "Montenegro" },
  { iata: "TIA", city: "Tirana", country: "Albania", alt: ["mother teresa"] },
  { iata: "SJJ", city: "Sarajevo", country: "Bosnia y Herzegovina" },
  { iata: "SKP", city: "Skopje", country: "Macedonia del Norte" },
  { iata: "CLJ", city: "Cluj-Napoca", country: "Rumanía", alt: ["cluj"] },
  { iata: "TSR", city: "Timișoara", country: "Rumanía" },

  // ── Bálticos (ampliación) ──
  { iata: "KUN", city: "Kaunas", country: "Lituania" },
  { iata: "PLQ", city: "Palanga", country: "Lituania" },

  // ── Cáucaso ──
  { iata: "GYD", city: "Bakú", country: "Azerbaiyán", alt: ["baku", "heydar aliyev"] },
  { iata: "EVN", city: "Ereván", country: "Armenia", alt: ["yerevan", "zvartnots"] },
  { iata: "TBS", city: "Tiflis", country: "Georgia", alt: ["tbilisi"] },
  { iata: "BUS", city: "Batumi", country: "Georgia" },

  // ── Europa regional (rutas ERJ/Vueling) ──
  { iata: "TRS", city: "Trieste", country: "Italia" },
  { iata: "AGB", city: "Augsburgo", country: "Alemania", alt: ["augsburg"] },
  { iata: "SPC", city: "La Palma", country: "España", alt: ["isla bonita", "canarias"] },

  // ── Azores / Madeira (ampliación) ──
  { iata: "TER", city: "Terceira", country: "Portugal", alt: ["lajes", "azores"] },

  // ── Francia regional ──
  { iata: "AJA", city: "Ajaccio", country: "Francia", alt: ["corcega", "corsica", "napoléon bonaparte"] },
  { iata: "BZR", city: "Béziers", country: "Francia", alt: ["beziers"] },
  { iata: "EBU", city: "Saint-Étienne", country: "Francia", alt: ["bouthéon"] },
  { iata: "PGF", city: "Perpiñán", country: "Francia", alt: ["perpignan"] },
  { iata: "BES", city: "Brest", country: "Francia", alt: ["bretagne"] },
  { iata: "TLN", city: "Toulon", country: "Francia", alt: ["hyères", "costa azul sur"] },
  { iata: "FNI", city: "Nîmes", country: "Francia", alt: ["nimes"] },
  { iata: "LDE", city: "Lourdes", country: "Francia", alt: ["tarbes"] },
  { iata: "RNS", city: "Rennes", country: "Francia" },
  { iata: "LIL", city: "Lille", country: "Francia" },

  // ── Reino Unido regional ──
  { iata: "ABZ", city: "Aberdeen", country: "Reino Unido", alt: ["scotland"] },
  { iata: "BFS", city: "Belfast Internacional", country: "Reino Unido", alt: ["northern ireland"] },
  { iata: "BHD", city: "Belfast City", country: "Reino Unido" },
  { iata: "LBA", city: "Leeds Bradford", country: "Reino Unido", alt: ["leeds"] },
  { iata: "EMA", city: "East Midlands", country: "Reino Unido", alt: ["nottingham"] },
  { iata: "SOU", city: "Southampton", country: "Reino Unido" },

  // ── Islandia / Escandinavia ampliación ──
  { iata: "MOL", city: "Molde", country: "Noruega" },
  { iata: "TOS", city: "Tromsø", country: "Noruega", alt: ["tromso", "auroras boreales", "northern lights"] },
  { iata: "KRS", city: "Kristiansand", country: "Noruega" },
  { iata: "SVG", city: "Stavanger", country: "Noruega", alt: ["pulpit rock"] },
  { iata: "AES", city: "Ålesund", country: "Noruega", alt: ["aalesund"] },
  { iata: "LPI", city: "Linköping", country: "Suecia", alt: ["linkoping"] },
  { iata: "UME", city: "Umeå", country: "Suecia", alt: ["umea"] },
  { iata: "LLA", city: "Luleå", country: "Suecia", alt: ["lulea"] },
  { iata: "KRN", city: "Kiruna", country: "Suecia", alt: ["ice hotel", "lappland"] },
  { iata: "TKU", city: "Turku", country: "Finlandia" },
  { iata: "OUL", city: "Oulu", country: "Finlandia" },
  { iata: "TMP", city: "Tampere", country: "Finlandia" },
  { iata: "RVN", city: "Rovaniemi", country: "Finlandia", alt: ["lapland", "santa claus", "laponia"] },
  { iata: "IVL", city: "Ivalo", country: "Finlandia", alt: ["inari", "lapland"] },

  // ── Rusia (hubs) ──
  { iata: "SVO", city: "Moscú Sheremétyevo", country: "Rusia", alt: ["moscow sheremetyevo", "moscú"] },
  { iata: "VKO", city: "Moscú Vnúkovo", country: "Rusia", alt: ["moscow vnukovo"] },
  { iata: "LED", city: "San Petersburgo", country: "Rusia", alt: ["st petersburg", "pulkovo", "leningrad"] },
  { iata: "KGD", city: "Kaliningrado", country: "Rusia", alt: ["kaliningrad"] },
  { iata: "AER", city: "Sochi", country: "Rusia", alt: ["mar negro"] },

  // ── EEUU (ampliación) ──
  { iata: "HOU", city: "Houston Hobby", country: "EE. UU.", alt: ["texas"] },
  { iata: "AUS", city: "Austin", country: "EE. UU.", alt: ["texas"] },
  { iata: "MEM", city: "Memphis", country: "EE. UU.", alt: ["tennessee"] },
  { iata: "ELP", city: "El Paso", country: "EE. UU." },
  { iata: "SLC", city: "Salt Lake City", country: "EE. UU.", alt: ["utah"] },
  { iata: "BOI", city: "Boise", country: "EE. UU.", alt: ["idaho"] },
  { iata: "OKC", city: "Oklahoma City", country: "EE. UU." },
  { iata: "RSW", city: "Fort Myers", country: "EE. UU.", alt: ["florida", "southwest florida"] },
  { iata: "JAX", city: "Jacksonville", country: "EE. UU.", alt: ["florida"] },
  { iata: "CHS", city: "Charleston", country: "EE. UU.", alt: ["south carolina"] },
  { iata: "BTV", city: "Burlington", country: "EE. UU.", alt: ["vermont"] },
  { iata: "BUF", city: "Búfalo", country: "EE. UU.", alt: ["buffalo", "niagara"] },
  { iata: "RDU", city: "Raleigh-Durham", country: "EE. UU.", alt: ["north carolina", "research triangle"] },
  { iata: "PNS", city: "Pensacola", country: "EE. UU.", alt: ["florida panhandle"] },
  // ── México / Centroamérica (ampliación) ──
  { iata: "HMO", city: "Hermosillo", country: "México" },
  { iata: "MID", city: "Mérida", country: "México", alt: ["yucatán"] },
  { iata: "OAX", city: "Oaxaca", country: "México" },
  { iata: "SAL", city: "San Salvador", country: "El Salvador" },
  { iata: "TGU", city: "Tegucigalpa", country: "Honduras" },
  { iata: "SAP", city: "San Pedro Sula", country: "Honduras" },
  { iata: "MGA", city: "Managua", country: "Nicaragua" },
  { iata: "GEO", city: "Georgetown", country: "Guyana" },
  { iata: "PBM", city: "Paramaribo", country: "Surinam" },

  // ── Sudamérica (ampliación) ──
  { iata: "MZA", city: "Mendoza", country: "Argentina", alt: ["aconcagua", "wine", "vino"] },
  { iata: "BRC", city: "Bariloche", country: "Argentina" },
  { iata: "FTE", city: "El Calafate", country: "Argentina", alt: ["perito moreno"] },
  { iata: "AQP", city: "Arequipa", country: "Perú", alt: ["colca"] },
  { iata: "SMR", city: "Santa Marta", country: "Colombia", alt: ["tayrona"] },
  { iata: "CLO", city: "Cali", country: "Colombia" },
  { iata: "BAQ", city: "Barranquilla", country: "Colombia" },

  // ── Caribe (ampliación) ──
  { iata: "AUA", city: "Aruba", country: "Aruba", alt: ["oranjestad"] },
  { iata: "CUR", city: "Curazao", country: "Curazao", alt: ["curacao", "willemstad"] },
  { iata: "BON", city: "Bonaire", country: "Países Bajos caribeños" },
  { iata: "SXM", city: "San Martín", country: "San Martín", alt: ["st maarten", "sint maarten", "princess juliana"] },
  { iata: "ANU", city: "Antigua", country: "Antigua y Barbuda" },
  { iata: "SKB", city: "Saint Kitts", country: "San Cristóbal y Nieves", alt: ["basseterre"] },
  { iata: "DOM", city: "Dominica", country: "Dominica", alt: ["roseau"] },
  { iata: "GND", city: "Granada", country: "Granada (Caribe)" },
  { iata: "FDF", city: "Fort-de-France", country: "Martinica", alt: ["martinique"] },
  { iata: "PTP", city: "Pointe-à-Pitre", country: "Guadalupe", alt: ["guadeloupe"] },
  { iata: "BGI", city: "Bridgetown", country: "Barbados" },
  { iata: "POP", city: "Puerto Plata", country: "República Dominicana" },
  { iata: "STI", city: "Santiago de los Caballeros", country: "República Dominicana" },
  { iata: "LRM", city: "La Romana", country: "República Dominicana" },
  { iata: "POS", city: "Puerto España", country: "Trinidad y Tobago", alt: ["port of spain"] },
  { iata: "GCM", city: "Gran Caimán", country: "Islas Caimán", alt: ["grand cayman", "george town"] },
  { iata: "PLS", city: "Providenciales", country: "Islas Turcas y Caicos", alt: ["turks and caicos"] },
  { iata: "FPO", city: "Freeport", country: "Bahamas" },
  { iata: "CAY", city: "Cayena", country: "Guayana Francesa", alt: ["cayenne"] },

  // ── Japón y Corea (ampliación) ──
  { iata: "SDJ", city: "Sendai", country: "Japón" },
  { iata: "HIJ", city: "Hiroshima", country: "Japón" },
  { iata: "FSZ", city: "Shizuoka", country: "Japón", alt: ["monte fuji"] },
  { iata: "OKJ", city: "Okayama", country: "Japón" },
  { iata: "CJU", city: "Jeju", country: "Corea del Sur", alt: ["cheju"] },
  { iata: "PUS", city: "Busan", country: "Corea del Sur", alt: ["gimhae"] },
  { iata: "TAE", city: "Daegu", country: "Corea del Sur" },

  // ── Groenlandia ──
  { iata: "GOH", city: "Nuuk", country: "Groenlandia", alt: ["godthåb"] },

  // ── África (ampliación) ──
  { iata: "TSE", city: "Astaná", country: "Kazajistán", alt: ["astana", "nur-sultan"] },
  { iata: "DLA", city: "Duala", country: "Camerún", alt: ["douala"] },
  { iata: "NSI", city: "Yaundé", country: "Camerún", alt: ["yaounde"] },
  { iata: "LBV", city: "Libreville", country: "Gabón" },
  { iata: "EBB", city: "Entebbe", country: "Uganda", alt: ["kampala"] },
  { iata: "KGL", city: "Kigali", country: "Ruanda" },
  { iata: "MPM", city: "Maputo", country: "Mozambique" },
  { iata: "APL", city: "Nampula", country: "Mozambique" },
  { iata: "MJV", city: "Murcia (RMU)", country: "España", alt: ["corvera", "cartagena"] },
];
