/**
 * country_hubs.ts — B7 (May 2026)
 *
 * Catálogo de países para SEO long-tail "/vuelos-a/[country]". Cada uno
 * con destinos top, mejor temporada, precio típico desde Madrid.
 */

export type CountryHub = {
  slug: string;
  name: string;
  emoji: string;
  region: string;
  capital: string;
  currency: string;
  language: string;
  best_months: string[];
  worst_months: string[];
  avg_price_madrid_eur: number;
  visa_status: string; // ref a /visados
  top_cities: { iata: string; name: string; teaser: string }[];
  intro: string;
  tips: string[];
  budget_per_day_eur: number;
};

export const COUNTRY_HUBS: CountryHub[] = [
  {
    slug: "japon",
    name: "Japón",
    emoji: "🗾",
    region: "Asia",
    capital: "Tokio",
    currency: "JPY",
    language: "Japonés",
    best_months: ["mar", "abr", "oct", "nov"],
    worst_months: ["jun", "jul", "ago"],
    avg_price_madrid_eur: 580,
    visa_status: "Sin visa 90 días",
    top_cities: [
      { iata: "NRT", name: "Tokio", teaser: "Capital cyberpunk + tradición" },
      { iata: "KIX", name: "Osaka", teaser: "Comida callejera + Kyoto cerca" },
      { iata: "FUK", name: "Fukuoka", teaser: "Puerta a Kyushu, ramen y onsen" },
    ],
    intro: "Japón es uno de los países más recompensantes para el viajero europeo. Sakura en marzo-abril, koyo (otoño rojo) en octubre-noviembre, y verano sofocante para evitar.",
    tips: ["JR Pass: rentable >2 viajes Tokio↔Osaka", "Suica/Pasmo: tarjeta IC para metro/conbinis", "Tax-free desde 5000¥ en tiendas con cartel"],
    budget_per_day_eur: 90,
  },
  {
    slug: "tailandia",
    name: "Tailandia",
    emoji: "🛕",
    region: "Asia",
    capital: "Bangkok",
    currency: "THB",
    language: "Tailandés",
    best_months: ["nov", "dic", "ene", "feb"],
    worst_months: ["may", "jun", "sep", "oct"],
    avg_price_madrid_eur: 510,
    visa_status: "Sin visa 30 días",
    top_cities: [
      { iata: "BKK", name: "Bangkok", teaser: "Templos + comida callejera + skyline" },
      { iata: "HKT", name: "Phuket", teaser: "Playas + acceso a Phi Phi/Krabi" },
      { iata: "CNX", name: "Chiang Mai", teaser: "Norte cultural, elefantes éticos" },
    ],
    intro: "Tailandia abierta, barata y bien conectada. Estación seca (nov-feb) ideal. Junio-octubre es monzón con mucha lluvia.",
    tips: ["Visa-free 30 días por aire", "Grab/Bolt vs taxi: mucho más barato", "Combini 7-Eleven están en cada esquina"],
    budget_per_day_eur: 35,
  },
  {
    slug: "marruecos",
    name: "Marruecos",
    emoji: "🌶️",
    region: "África",
    capital: "Rabat",
    currency: "MAD",
    language: "Árabe + francés",
    best_months: ["mar", "abr", "may", "oct"],
    worst_months: ["jul", "ago"],
    avg_price_madrid_eur: 90,
    visa_status: "Sin visa 90 días",
    top_cities: [
      { iata: "RAK", name: "Marrakech", teaser: "Medina, riads, Atlas" },
      { iata: "FEZ", name: "Fez", teaser: "Medina más antigua del mundo" },
      { iata: "AGA", name: "Agadir", teaser: "Playa + acceso a Essaouira" },
    ],
    intro: "Marruecos es el destino exótico más cercano para España. Vuelos Ryanair desde 30€. Primavera y otoño son la mejor época.",
    tips: ["Riads > hoteles para inmersión", "Regatear es esperado en zocos", "Petits taxis con taxímetro siempre"],
    budget_per_day_eur: 30,
  },
  {
    slug: "italia",
    name: "Italia",
    emoji: "🇮🇹",
    region: "Europa",
    capital: "Roma",
    currency: "EUR",
    language: "Italiano",
    best_months: ["abr", "may", "jun", "sep", "oct"],
    worst_months: ["jul", "ago"],
    avg_price_madrid_eur: 75,
    visa_status: "UE — DNI",
    top_cities: [
      { iata: "FCO", name: "Roma", teaser: "Coliseo, Vaticano, Trastevere" },
      { iata: "MXP", name: "Milán", teaser: "Moda, lagos, puerta a los Alpes" },
      { iata: "NAP", name: "Nápoles", teaser: "Pizza original + Pompeya" },
      { iata: "VCE", name: "Venecia", teaser: "Canales, sin coches, único" },
    ],
    intro: "Italia es probablemente el mejor balance precio-experiencia de Europa. Cualquier mes excepto agosto (turistas + calor extremo).",
    tips: ["Trenitalia anticipado 50% descuento", "Coperto en restaurantes (€2-3 cubierto)", "Cafe expreso: 1€ de pie en barra, 4€ sentado"],
    budget_per_day_eur: 75,
  },
  {
    slug: "estados-unidos",
    name: "Estados Unidos",
    emoji: "🇺🇸",
    region: "Norteamérica",
    capital: "Washington DC",
    currency: "USD",
    language: "Inglés",
    best_months: ["may", "jun", "sep", "oct"],
    worst_months: ["dic", "ene"],
    avg_price_madrid_eur: 380,
    visa_status: "ESTA 21€ · 90 días",
    top_cities: [
      { iata: "JFK", name: "Nueva York", teaser: "Manhattan, Brooklyn, museos" },
      { iata: "MIA", name: "Miami", teaser: "Playa + Cuba + Cayos" },
      { iata: "LAX", name: "Los Ángeles", teaser: "Hollywood + Joshua Tree" },
      { iata: "SFO", name: "San Francisco", teaser: "Golden Gate + Yosemite" },
    ],
    intro: "Vuelos USA siempre disponibles a precios razonables desde Madrid (~380€) y BCN (~350€). ESTA obligatoria, recordar 6 meses pasaporte.",
    tips: ["ESTA online minutos antes (21$)", "Propina 18-20% restaurantes", "Tax añadido al precio en cada estado"],
    budget_per_day_eur: 150,
  },
  {
    slug: "mexico",
    name: "México",
    emoji: "🇲🇽",
    region: "Latam",
    capital: "Ciudad de México",
    currency: "MXN",
    language: "Español",
    best_months: ["nov", "dic", "ene", "feb", "mar", "abr"],
    worst_months: ["jul", "ago", "sep"],
    avg_price_madrid_eur: 480,
    visa_status: "Sin visa 180 días",
    top_cities: [
      { iata: "MEX", name: "CDMX", teaser: "Comida + arte + Teotihuacán" },
      { iata: "CUN", name: "Cancún", teaser: "Caribe + Tulum + cenotes" },
      { iata: "OAX", name: "Oaxaca", teaser: "Cultura indígena + mezcal" },
    ],
    intro: "México combina playa Caribe (Yucatán) con altiplano cultural (CDMX, Oaxaca). Temporada seca nov-abril, monzón verano.",
    tips: ["No bebas agua de grifo", "FMM al llegar, guárdalo (lo piden al salir)", "Uber > taxi en CDMX/Cancún"],
    budget_per_day_eur: 50,
  },
  {
    slug: "indonesia",
    name: "Indonesia",
    emoji: "🏝️",
    region: "Asia",
    capital: "Yakarta",
    currency: "IDR",
    language: "Bahasa Indonesia",
    best_months: ["abr", "may", "jun", "jul", "ago", "sep"],
    worst_months: ["dic", "ene", "feb"],
    avg_price_madrid_eur: 620,
    visa_status: "VoA 30 días · 32€",
    top_cities: [
      { iata: "DPS", name: "Bali", teaser: "Ubud + Canggu + Uluwatu" },
      { iata: "CGK", name: "Yakarta", teaser: "Hub para Java/Komodo" },
    ],
    intro: "Indonesia = Bali + 17000 islas más. Bali es el más accesible: VoA al llegar, vuelos directos desde Madrid (1 escala).",
    tips: ["VoA 500K IDR cash o online previa", "Gojek/Grab para moto-taxi (10x más barato)", "Lluvia diaria nov-feb pero corta"],
    budget_per_day_eur: 30,
  },
  {
    slug: "francia",
    name: "Francia",
    emoji: "🇫🇷",
    region: "Europa",
    capital: "París",
    currency: "EUR",
    language: "Francés",
    best_months: ["abr", "may", "jun", "sep"],
    worst_months: ["nov", "dic", "ene"],
    avg_price_madrid_eur: 75,
    visa_status: "UE — DNI",
    top_cities: [
      { iata: "CDG", name: "París", teaser: "Eiffel + Marais + Montmartre" },
      { iata: "MRS", name: "Marsella", teaser: "Mediterráneo + Calanques" },
      { iata: "NCE", name: "Niza", teaser: "Costa Azul + Mónaco" },
    ],
    intro: "Francia es accesible todo el año desde España. París cualquier mes salvo agosto (parisinos de vacaciones, todo cerrado).",
    tips: ["Carnet jeune si <26 años en SNCF", "Pasaporte gastronómico en barrios", "Museos gratuitos primer domingo de mes"],
    budget_per_day_eur: 100,
  },
  {
    slug: "portugal",
    name: "Portugal",
    emoji: "🇵🇹",
    region: "Europa",
    capital: "Lisboa",
    currency: "EUR",
    language: "Portugués",
    best_months: ["abr", "may", "jun", "sep", "oct"],
    worst_months: ["jul", "ago"],
    avg_price_madrid_eur: 70,
    visa_status: "UE — DNI",
    top_cities: [
      { iata: "LIS", name: "Lisboa", teaser: "Alfama, Belém, miradores" },
      { iata: "OPO", name: "Oporto", teaser: "Vino + Douro + comida" },
      { iata: "FAO", name: "Faro/Algarve", teaser: "Playa atlántica + acantilados" },
    ],
    intro: "Portugal es probablemente el destino europeo con mejor relación calidad-precio. Vuelos baratos Madrid-Lisboa todo el año.",
    tips: ["Lisboa ya no es el secreto barato — pero sigue 30% más barato que Madrid", "Tram 28 turístico siempre lleno: ve en el 12 o 24", "Pasteles de Belém vs cualquier otro = imperdible"],
    budget_per_day_eur: 65,
  },
  {
    slug: "egipto",
    name: "Egipto",
    emoji: "🇪🇬",
    region: "África",
    capital: "El Cairo",
    currency: "EGP",
    language: "Árabe",
    best_months: ["nov", "dic", "ene", "feb", "mar"],
    worst_months: ["jul", "ago"],
    avg_price_madrid_eur: 280,
    visa_status: "VoA 30 días · 23€",
    top_cities: [
      { iata: "CAI", name: "El Cairo", teaser: "Pirámides + Museo Egipcio" },
      { iata: "HRG", name: "Hurghada", teaser: "Mar Rojo + buceo" },
      { iata: "LXR", name: "Luxor", teaser: "Valle de los Reyes + Karnak" },
    ],
    intro: "Egipto es uno de los países más impresionantes del mundo a precios extremadamente bajos. Invierno (nov-mar) es la única época viable.",
    tips: ["VoA 25 USD en aeropuerto", "Crucero Nilo Luxor-Aswan 4 noches: experiencia clave", "Regatear obligado en mercados"],
    budget_per_day_eur: 40,
  },
  {
    slug: "turquia",
    name: "Turquía",
    emoji: "🇹🇷",
    region: "Europa/Asia",
    capital: "Ankara",
    currency: "TRY",
    language: "Turco",
    best_months: ["abr", "may", "jun", "sep", "oct"],
    worst_months: ["jul", "ago"],
    avg_price_madrid_eur: 165,
    visa_status: "Sin visa 90 días",
    top_cities: [
      { iata: "IST", name: "Estambul", teaser: "Hagia Sofía + bazares + Bósforo" },
      { iata: "AYT", name: "Antalya", teaser: "Costa turquesa + ruinas" },
      { iata: "ASR", name: "Capadocia", teaser: "Globos + casas-cueva" },
    ],
    intro: "Turquía liberalizó visas en 2020. Lira muy débil = país barato a pesar de turismo. Estambul + Capadocia = ruta clásica.",
    tips: ["Visa-free desde 2020", "Lira muy depreciada: paga en dólares cuando puedas", "Globos Capadocia al amanecer = imprescindible"],
    budget_per_day_eur: 35,
  },
  {
    slug: "argentina",
    name: "Argentina",
    emoji: "🇦🇷",
    region: "Latam",
    capital: "Buenos Aires",
    currency: "ARS",
    language: "Español",
    best_months: ["sep", "oct", "nov", "mar", "abr"],
    worst_months: ["jul", "ago"],
    avg_price_madrid_eur: 720,
    visa_status: "Sin visa 90 días",
    top_cities: [
      { iata: "EZE", name: "Buenos Aires", teaser: "Tango, San Telmo, Palermo" },
      { iata: "USH", name: "Ushuaia", teaser: "Fin del mundo, glaciares" },
      { iata: "BRC", name: "Bariloche", teaser: "Lagos + Andes + chocolate" },
    ],
    intro: "Argentina es destino premium pero su moneda débil lo hace asequible. Estaciones invertidas: nuestro invierno es su verano.",
    tips: ["Cambiar a 'dólar blue' si pagas cash USD/EUR", "Carne argentina: parrillada >300% más barata que España", "AR aerolíneas internas baratas para distancias largas"],
    budget_per_day_eur: 60,
  },
];

export function getCountryBySlug(slug: string): CountryHub | undefined {
  return COUNTRY_HUBS.find((c) => c.slug === slug);
}
