/**
 * idiomas_catalog.ts — SUPERSESSION (24 may 2026)
 *
 * Frases básicas para viajeros españoles en idiomas locales. 12 países
 * top con 12 frases cada uno (saludo, cortesía, números, restaurante,
 * navegación, emergencia).
 */

export interface FraseEntry {
  es: string; // "Hola"
  local: string; // "こんにちは"
  pronuncia?: string; // "konnichiwa"
}

export interface IdiomaPais {
  slug: string;
  pais: string;
  idiomaName: string; // "Japonés"
  emoji: string;
  destinoSlug?: string;
  oneLiner: string;
  frases: FraseEntry[];
  tip: string;
}

export const IDIOMAS_CATALOG: IdiomaPais[] = [
  {
    slug: "japon",
    pais: "Japón",
    idiomaName: "Japonés",
    emoji: "🇯🇵",
    destinoSlug: "japon",
    oneLiner: "Saber 5 frases en japonés transforma tu viaje. Los japoneses valoran el esfuerzo enorme.",
    frases: [
      { es: "Hola", local: "こんにちは", pronuncia: "konnichiwa" },
      { es: "Gracias", local: "ありがとう", pronuncia: "arigatou" },
      { es: "Disculpe", local: "すみません", pronuncia: "sumimasen" },
      { es: "Sí / No", local: "はい / いいえ", pronuncia: "hai / iie" },
      { es: "Por favor", local: "おねがいします", pronuncia: "onegaishimasu" },
      { es: "¿Cuánto cuesta?", local: "いくらですか？", pronuncia: "ikura desu ka?" },
      { es: "La cuenta, por favor", local: "おかいけい おねがいします", pronuncia: "okaikei onegaishimasu" },
      { es: "Estación de tren", local: "えき", pronuncia: "eki" },
      { es: "Baño", local: "トイレ", pronuncia: "toire" },
      { es: "Agua", local: "みず", pronuncia: "mizu" },
      { es: "No entiendo", local: "わかりません", pronuncia: "wakarimasen" },
      { es: "¿Habla inglés?", local: "えいご はなせますか？", pronuncia: "eigo hanasemasu ka?" },
    ],
    tip: "Inclina la cabeza ligeramente al decir 'arigatou'. El gesto multiplica el efecto.",
  },
  {
    slug: "tailandia",
    pais: "Tailandia",
    idiomaName: "Tailandés",
    emoji: "🇹🇭",
    destinoSlug: "tailandia",
    oneLiner: "Las palabras femeninas terminan en 'ka', masculinas en 'krap'. Marca enorme respeto.",
    frases: [
      { es: "Hola", local: "สวัสดี", pronuncia: "sawadi krap (♂) / sawadi ka (♀)" },
      { es: "Gracias", local: "ขอบคุณ", pronuncia: "khob khun" },
      { es: "Disculpe", local: "ขอโทษ", pronuncia: "kho thot" },
      { es: "Sí / No", local: "ใช่ / ไม่", pronuncia: "chai / mai" },
      { es: "¿Cuánto cuesta?", local: "เท่าไหร่?", pronuncia: "tao rai?" },
      { es: "Demasiado caro", local: "แพง", pronuncia: "phaeng" },
      { es: "Sin picante", local: "ไม่เผ็ด", pronuncia: "mai phet" },
      { es: "Agua", local: "น้ำ", pronuncia: "nam" },
      { es: "Baño", local: "ห้องน้ำ", pronuncia: "hong nam" },
      { es: "Hotel", local: "โรงแรม", pronuncia: "rong raem" },
      { es: "Taxi", local: "แท็กซี่", pronuncia: "tek si" },
      { es: "Delicioso", local: "อร่อย", pronuncia: "aroi" },
    ],
    tip: "'Mai phet' (sin picante) lo necesitarás 5 veces al día. Aprende esa primero.",
  },
  {
    slug: "marruecos",
    pais: "Marruecos",
    idiomaName: "Árabe marroquí + francés",
    emoji: "🇲🇦",
    destinoSlug: "marruecos",
    oneLiner: "Francés funciona en zonas turísticas. Saber 3 palabras árabes ayuda en zoco.",
    frases: [
      { es: "Hola (paz contigo)", local: "السلام عليكم", pronuncia: "as-salamu alaykum" },
      { es: "Gracias", local: "شكرا", pronuncia: "shukran" },
      { es: "Sí / No", local: "نعم / لا", pronuncia: "naam / la" },
      { es: "¿Cuánto?", local: "بشحال", pronuncia: "bshhal" },
      { es: "Demasiado caro", local: "غالي بزاف", pronuncia: "ghali bzaf" },
      { es: "Agua", local: "ماء", pronuncia: "ma" },
      { es: "Té", local: "أتاي", pronuncia: "atay" },
      { es: "Hotel", local: "فندق", pronuncia: "funduq" },
      { es: "Bien, gracias (francés)", local: "Bien, merci", pronuncia: "biang mersi" },
      { es: "No, gracias (francés)", local: "Non merci", pronuncia: "non mersi" },
      { es: "Sólo miro", local: "أنا أتفرج", pronuncia: "ana atfarraj" },
      { es: "Insh'Allah", local: "إن شاء الله", pronuncia: "insh'allah (=si Dios quiere)" },
    ],
    tip: "Insh'Allah cubre 'tal vez', 'a ver si pasa', 'no estoy seguro'. Útil para esquivar promesas.",
  },
  {
    slug: "indonesia",
    pais: "Indonesia",
    idiomaName: "Bahasa Indonesia",
    emoji: "🇮🇩",
    destinoSlug: "bali",
    oneLiner: "Bahasa es fácil — sin género, sin conjugaciones. En Bali se mezcla con balinés.",
    frases: [
      { es: "Hola", local: "Halo", pronuncia: "halo" },
      { es: "Buenos días", local: "Selamat pagi", pronuncia: "selamat pagi" },
      { es: "Gracias", local: "Terima kasih", pronuncia: "terima kasi" },
      { es: "Por favor", local: "Tolong", pronuncia: "tolong" },
      { es: "Sí / No", local: "Ya / Tidak", pronuncia: "ya / tidak" },
      { es: "¿Cuánto cuesta?", local: "Berapa harganya?", pronuncia: "berapa harganya" },
      { es: "Caro", local: "Mahal", pronuncia: "mahal" },
      { es: "Más barato", local: "Lebih murah", pronuncia: "lebij murah" },
      { es: "Agua", local: "Air", pronuncia: "ayer" },
      { es: "No picante", local: "Tidak pedas", pronuncia: "tidak pedas" },
      { es: "Delicioso", local: "Enak", pronuncia: "enak" },
      { es: "Adiós", local: "Selamat tinggal", pronuncia: "selamat tingal" },
    ],
    tip: "En Bali añade 'pak' (señor) o 'ibu' (señora) — multiplica respeto local.",
  },
  {
    slug: "vietnam",
    pais: "Vietnam",
    idiomaName: "Vietnamita",
    emoji: "🇻🇳",
    destinoSlug: "vietnam",
    oneLiner: "Tonos clave — la misma sílaba con tono diferente significa cosas distintas.",
    frases: [
      { es: "Hola", local: "Xin chào", pronuncia: "sin chao" },
      { es: "Gracias", local: "Cảm ơn", pronuncia: "kam un" },
      { es: "Sí / No", local: "Có / Không", pronuncia: "ko / khong" },
      { es: "¿Cuánto?", local: "Bao nhiêu?", pronuncia: "bao nyeu" },
      { es: "Caro", local: "Đắt quá", pronuncia: "dat kua" },
      { es: "Más barato", local: "Rẻ hơn", pronuncia: "ze hon" },
      { es: "Agua", local: "Nước", pronuncia: "nuok" },
      { es: "Cerveza", local: "Bia", pronuncia: "bia" },
      { es: "Café", local: "Cà phê", pronuncia: "ka fe" },
      { es: "Delicioso", local: "Ngon", pronuncia: "ngon" },
      { es: "Adiós", local: "Tạm biệt", pronuncia: "tam biet" },
      { es: "Sin picante", local: "Không cay", pronuncia: "khong kay" },
    ],
    tip: "Café vietnamita es muy fuerte (robusta). Pide 'cà phê sữa đá' (café leche hielo).",
  },
  {
    slug: "turquia",
    pais: "Turquía",
    idiomaName: "Turco",
    emoji: "🇹🇷",
    destinoSlug: "estambul",
    oneLiner: "Turco usa alfabeto latino moderno desde Atatürk — fácil de leer y aproximar.",
    frases: [
      { es: "Hola", local: "Merhaba", pronuncia: "merjabá" },
      { es: "Gracias", local: "Teşekkür ederim", pronuncia: "teshekur ederim" },
      { es: "Por favor", local: "Lütfen", pronuncia: "lyutfen" },
      { es: "Sí / No", local: "Evet / Hayır", pronuncia: "evet / jair" },
      { es: "¿Cuánto?", local: "Ne kadar?", pronuncia: "ne kadar" },
      { es: "Caro", local: "Pahalı", pronuncia: "pajali" },
      { es: "Té", local: "Çay", pronuncia: "chai" },
      { es: "Café turco", local: "Türk kahvesi", pronuncia: "turk kajvesi" },
      { es: "Agua", local: "Su", pronuncia: "su" },
      { es: "La cuenta", local: "Hesap", pronuncia: "jesap" },
      { es: "Bonito", local: "Güzel", pronuncia: "gyuzel" },
      { es: "Salud (brindis)", local: "Şerefe", pronuncia: "sherefe" },
    ],
    tip: "Si te ofrecen té (çay) — NUNCA lo rechaces. Es ritual social clave en Turquía.",
  },
  {
    slug: "brasil",
    pais: "Brasil",
    idiomaName: "Portugués brasileño",
    emoji: "🇧🇷",
    oneLiner: "El portugués no es español con acento. Pronunciación nasal es la diferencia clave.",
    frases: [
      { es: "Hola", local: "Olá", pronuncia: "olá" },
      { es: "Gracias", local: "Obrigado (♂) / Obrigada (♀)", pronuncia: "obrigado/obrigada" },
      { es: "Por favor", local: "Por favor", pronuncia: "por favor" },
      { es: "Sí / No", local: "Sim / Não", pronuncia: "sim / nau" },
      { es: "¿Cuánto cuesta?", local: "Quanto custa?", pronuncia: "kuanto kusta" },
      { es: "La cuenta", local: "A conta", pronuncia: "a conta" },
      { es: "Agua", local: "Água", pronuncia: "agua" },
      { es: "Cerveza", local: "Cerveja", pronuncia: "serveja" },
      { es: "Café con leche", local: "Pingado", pronuncia: "pingado" },
      { es: "Genial / Guay", local: "Legal", pronuncia: "legaw" },
      { es: "Disculpe", local: "Desculpe", pronuncia: "deskulpi" },
      { es: "Salud", local: "Saúde", pronuncia: "saude" },
    ],
    tip: "Brasileños mezclan español con cariño — pero ojo: 'embarazada' en portugués significa 'avergonzada'.",
  },
  {
    slug: "china",
    pais: "China",
    idiomaName: "Mandarín",
    emoji: "🇨🇳",
    oneLiner: "Mandarín usa tonos — 'ma' tiene 4 significados según tono. Anota frases en pinyin.",
    frases: [
      { es: "Hola", local: "你好", pronuncia: "nǐ hǎo" },
      { es: "Gracias", local: "谢谢", pronuncia: "xièxie" },
      { es: "Sí / No", local: "是 / 不是", pronuncia: "shì / bú shì" },
      { es: "¿Cuánto?", local: "多少钱?", pronuncia: "duōshǎo qián" },
      { es: "Caro", local: "太贵了", pronuncia: "tài guì le" },
      { es: "Agua", local: "水", pronuncia: "shuǐ" },
      { es: "Té", local: "茶", pronuncia: "chá" },
      { es: "Cerveza", local: "啤酒", pronuncia: "píjiǔ" },
      { es: "La cuenta", local: "买单", pronuncia: "mǎidān" },
      { es: "No picante", local: "不辣", pronuncia: "bù là" },
      { es: "Delicioso", local: "好吃", pronuncia: "hǎochī" },
      { es: "Adiós", local: "再见", pronuncia: "zàijiàn" },
    ],
    tip: "Lleva WeChat instalado + Google Translate offline mandarín. WiFi en China bloquea Google fuera.",
  },
  {
    slug: "alemania",
    pais: "Alemania",
    idiomaName: "Alemán",
    emoji: "🇩🇪",
    oneLiner: "Alemanes valoran precisión. 'Bitte' (por favor) y 'Danke' (gracias) suavizan todo.",
    frases: [
      { es: "Hola", local: "Hallo", pronuncia: "jalo" },
      { es: "Gracias", local: "Danke", pronuncia: "danke" },
      { es: "Por favor / De nada", local: "Bitte", pronuncia: "bite" },
      { es: "Sí / No", local: "Ja / Nein", pronuncia: "ya / nain" },
      { es: "¿Cuánto cuesta?", local: "Wie viel kostet?", pronuncia: "vi fil kostet" },
      { es: "La cuenta", local: "Die Rechnung", pronuncia: "di rejnung" },
      { es: "Cerveza", local: "Bier", pronuncia: "bier" },
      { es: "Agua sin gas", local: "Stilles Wasser", pronuncia: "shtiles vaser" },
      { es: "Disculpe", local: "Entschuldigung", pronuncia: "ent-shuldigung" },
      { es: "No entiendo", local: "Ich verstehe nicht", pronuncia: "ij ferstee niit" },
      { es: "Estación", local: "Bahnhof", pronuncia: "ban-jof" },
      { es: "Salud", local: "Prost", pronuncia: "prost" },
    ],
    tip: "En restaurante alemán el camarero NO viene hasta que llamas. Dí 'Entschuldigung' suave.",
  },
  {
    slug: "italia",
    pais: "Italia",
    idiomaName: "Italiano",
    emoji: "🇮🇹",
    oneLiner: "Italiano se parece al español pero atención al 'permesso' y 'prego' — uso muy diferente.",
    frases: [
      { es: "Hola / Adiós", local: "Ciao", pronuncia: "chao" },
      { es: "Buenos días", local: "Buongiorno", pronuncia: "buon-yorno" },
      { es: "Gracias", local: "Grazie", pronuncia: "grátsie" },
      { es: "De nada / Por favor", local: "Prego", pronuncia: "prego" },
      { es: "Sí / No", local: "Sì / No", pronuncia: "si / no" },
      { es: "¿Cuánto cuesta?", local: "Quanto costa?", pronuncia: "kuanto kosta" },
      { es: "La cuenta", local: "Il conto", pronuncia: "il konto" },
      { es: "Agua con gas", local: "Acqua frizzante", pronuncia: "akua fritsante" },
      { es: "Café (espresso)", local: "Un caffè", pronuncia: "un kafé" },
      { es: "Delicioso", local: "Delizioso", pronuncia: "delitsioso" },
      { es: "Disculpe / Permiso", local: "Permesso", pronuncia: "permeso" },
      { es: "Salud", local: "Cin cin", pronuncia: "chin chin" },
    ],
    tip: "NUNCA pidas cappuccino después de las 11h — los italianos lo consideran sólo desayuno.",
  },
  {
    slug: "grecia",
    pais: "Grecia",
    idiomaName: "Griego moderno",
    emoji: "🇬🇷",
    oneLiner: "El alfabeto griego intimida pero las palabras turísticas son fáciles.",
    frases: [
      { es: "Hola / Adiós", local: "Γεια σου", pronuncia: "yasu" },
      { es: "Gracias", local: "Ευχαριστώ", pronuncia: "ef-jaristó" },
      { es: "Por favor / De nada", local: "Παρακαλώ", pronuncia: "parakaló" },
      { es: "Sí / No", local: "Ναι / Όχι", pronuncia: "ne / oji (ojo: ne=sí)" },
      { es: "¿Cuánto cuesta?", local: "Πόσο κάνει?", pronuncia: "poso kanei" },
      { es: "La cuenta", local: "Τον λογαριασμό", pronuncia: "ton logariasmó" },
      { es: "Agua", local: "Νερό", pronuncia: "neró" },
      { es: "Vino", local: "Κρασί", pronuncia: "krasí" },
      { es: "Cerveza", local: "Μπύρα", pronuncia: "bíra" },
      { es: "Delicioso", local: "Νόστιμο", pronuncia: "nóstimo" },
      { es: "Buenas noches", local: "Καληνύχτα", pronuncia: "kali-níjta" },
      { es: "Salud", local: "Στην υγειά μας", pronuncia: "stin iyiá mas" },
    ],
    tip: "'Ne' en griego significa SÍ — confunde a españoles. No es 'no'.",
  },
  {
    slug: "argentina",
    pais: "Argentina",
    idiomaName: "Español rioplatense",
    emoji: "🇦🇷",
    destinoSlug: "buenos-aires",
    oneLiner: "Mismo idioma pero vocabulario y entonación distintos. 'Vos' reemplaza 'tú'.",
    frases: [
      { es: "Hola, ¿cómo estás?", local: "Hola, ¿cómo andás?", pronuncia: "kómo andás" },
      { es: "Bien, gracias", local: "Bien, dale", pronuncia: "bien, dale" },
      { es: "Sí / No", local: "Sí / No (igual)", pronuncia: "" },
      { es: "¿Cuánto sale?", local: "¿Cuánto sale?", pronuncia: "(en lugar de 'cuánto cuesta')" },
      { es: "Genial", local: "Bárbaro", pronuncia: "bárbaro" },
      { es: "Por favor", local: "Dale", pronuncia: "dale (informal universal)" },
      { es: "Bebida (no agua)", local: "Gaseosa", pronuncia: "gaseosa (refresco)" },
      { es: "Aguacate", local: "Palta", pronuncia: "palta" },
      { es: "Fresa", local: "Frutilla", pronuncia: "frutilla" },
      { es: "Chaqueta", local: "Campera", pronuncia: "kampera" },
      { es: "Estoy mareado", local: "Tengo bocho", pronuncia: "tengo bocho" },
      { es: "Brindis (vino)", local: "Salud", pronuncia: "" },
    ],
    tip: "'Vos' se conjuga distinto: 'vos podés', 'vos tenés', 'vos sos'. Practícalo o suenas extranjero.",
  },
];

export const IDIOMAS_SLUGS: string[] = IDIOMAS_CATALOG.map((i) => i.slug);

export function getIdioma(slug: string): IdiomaPais | undefined {
  return IDIOMAS_CATALOG.find((i) => i.slug === slug.toLowerCase());
}
