/**
 * seed_diversifier.ts — fase ff-C1
 *
 * Frontend rotation guard: si /api/deals devuelve solo deals de un mes
 * (síntoma del seed legacy hardcodeado a jun-2026), reemplaza el catálogo
 * por un seed local TS con 30+ deals cubriendo Jul-2026 → Jun-2027.
 *
 * Por qué un fallback frontend en vez de esperar al VPS:
 *  - VPS systemd timer corre cada 6h. Hasta que pull el seed_deals.py nuevo
 *    desde GitHub (workflow vercel-deploy o manual), pasarán horas.
 *  - El usuario quería "ver chollos en otros meses" YA, no en 6h.
 *  - Este módulo se desactiva automáticamente cuando el motor real (o el
 *    VPS seed actualizado) devuelve ≥3 meses distintos.
 *
 * El fallback NO sobrescribe deals legítimos — sólo entra cuando se cumple:
 *  - todos los deals tienen el mismo mes (single-month signal)
 *  - O hay <8 deals en total (signal de motor caído)
 *
 * Cuando el motor real esté operativo con datos reales y diversos, este
 * código pasa a ser no-op transparente.
 */

import type { Deal } from "./api";

// Catálogo TS espejo de api/seed_deals.py (mismo orden y datos).
// Mantenerlo sincronizado: si actualizas uno, actualiza el otro.
// El seed Python es la fuente of truth (lo consume el VPS); este es backup.

// Template tipo extendido: airline_code es interno (no en Deal interface) —
// lo usa enhanceDealBookingUrl para generar URLs directas Ryanair/easyJet/Wizz.
// Lo dropeamos antes de devolver al frontend.
type CatalogTemplate = Partial<Deal> & {
  _key: string;
  airline_code?: string;
};

const FALLBACK_CATALOG: CatalogTemplate[] = [
  // JUL 2026
  { _key: "jul-kef", type: "flight", headline: "Madrid → Reikiavik con Wizz desde 119€",
    origin: "MAD", destination: "KEF", city_from: "Madrid", city_to: "Reikiavik",
    country_to: "Islandia", region: "Europa",
    price_eur: 119, savings_pct: 58, savings_eur: 165, nights: 5,
    date_out: "2026-07-12", date_ret: "2026-07-17",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Wizz Air",
    stops: 0, duration_min: 290, score: 88 },
  { _key: "jul-arn", type: "flight", headline: "Barcelona → Estocolmo con Vueling desde 89€",
    origin: "BCN", destination: "ARN", city_from: "Barcelona", city_to: "Estocolmo",
    country_to: "Suecia", region: "Europa",
    price_eur: 89, savings_pct: 42, savings_eur: 65, nights: 4,
    date_out: "2026-07-04", date_ret: "2026-07-08",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Vueling",
    stops: 0, duration_min: 220, score: 75 },

  // AGO 2026
  { _key: "ago-edi", type: "flight", headline: "Barcelona → Edimburgo con Ryanair desde 49€",
    origin: "BCN", destination: "EDI", city_from: "Barcelona", city_to: "Edimburgo",
    country_to: "Reino Unido", region: "Europa",
    price_eur: 49, savings_pct: 51, savings_eur: 51, nights: 3,
    date_out: "2026-08-08", date_ret: "2026-08-11",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Ryanair",
    stops: 0, duration_min: 165, score: 91 },
  { _key: "ago-bgo", type: "flight", headline: "Madrid → Bergen con SAS desde 165€",
    origin: "MAD", destination: "BGO", city_from: "Madrid", city_to: "Bergen",
    country_to: "Noruega", region: "Europa",
    price_eur: 165, savings_pct: 33, savings_eur: 82, nights: 5,
    date_out: "2026-08-15", date_ret: "2026-08-20",
    classification: "OFERTA", cabin: "economy",
    airline_name: "SAS",
    stops: 1, duration_min: 290, score: 70 },

  // SEP 2026
  { _key: "sep-nrt-business", type: "flight", headline: "Madrid → Tokio business con Iberia desde 1.395€",
    origin: "MAD", destination: "NRT", city_from: "Madrid", city_to: "Tokio",
    country_to: "Japón", region: "Asia",
    price_eur: 1395, savings_pct: 64, savings_eur: 2480, nights: 9,
    date_out: "2026-09-12", date_ret: "2026-09-21",
    classification: "CRÍTICO", cabin: "business",
    airline_name: "Iberia",
    stops: 1, duration_min: 920, score: 96 },
  { _key: "sep-bkk", type: "flight", headline: "Barcelona → Bangkok con Qatar desde 525€",
    origin: "BCN", destination: "BKK", city_from: "Barcelona", city_to: "Bangkok",
    country_to: "Tailandia", region: "Asia",
    price_eur: 525, savings_pct: 41, savings_eur: 365, nights: 12,
    date_out: "2026-09-20", date_ret: "2026-10-02",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Qatar Airways",
    stops: 1, duration_min: 920, score: 80 },
  { _key: "sep-rak", type: "flight", headline: "Madrid → Marrakech con Ryanair desde 35€",
    origin: "MAD", destination: "RAK", city_from: "Madrid", city_to: "Marrakech",
    country_to: "Marruecos", region: "África",
    price_eur: 35, savings_pct: 64, savings_eur: 65, nights: 4,
    date_out: "2026-09-26", date_ret: "2026-09-30",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Ryanair",
    stops: 0, duration_min: 175, score: 89 },

  // OCT 2026
  { _key: "oct-lis", type: "flight", headline: "Madrid → Lisboa con TAP weekend Pilar desde 78€",
    origin: "MAD", destination: "LIS", city_from: "Madrid", city_to: "Lisboa",
    country_to: "Portugal", region: "Europa",
    price_eur: 78, savings_pct: 28, savings_eur: 32, nights: 3,
    date_out: "2026-10-09", date_ret: "2026-10-12",
    classification: "OFERTA", cabin: "economy",
    airline_name: "TAP Portugal",
    stops: 0, duration_min: 75, score: 72 },
  { _key: "oct-ist", type: "flight", headline: "Barcelona → Estambul con Turkish desde 195€",
    origin: "BCN", destination: "IST", city_from: "Barcelona", city_to: "Estambul",
    country_to: "Turquía", region: "Asia",
    price_eur: 195, savings_pct: 35, savings_eur: 105, nights: 5,
    date_out: "2026-10-15", date_ret: "2026-10-20",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Turkish Airlines",
    stops: 0, duration_min: 215, score: 76 },
  { _key: "oct-syd-business", type: "flight", headline: "Madrid → Sídney business con Qatar desde 2.495€",
    origin: "MAD", destination: "SYD", city_from: "Madrid", city_to: "Sídney",
    country_to: "Australia", region: "Oceanía",
    price_eur: 2495, savings_pct: 58, savings_eur: 3450, nights: 14,
    date_out: "2026-10-04", date_ret: "2026-10-18",
    classification: "CRÍTICO", cabin: "business",
    airline_name: "Qatar Airways",
    stops: 1, duration_min: 1450, score: 95 },

  // NOV 2026
  { _key: "nov-prg", type: "flight", headline: "Madrid → Praga con Ryanair desde 39€",
    origin: "MAD", destination: "PRG", city_from: "Madrid", city_to: "Praga",
    country_to: "Chequia", region: "Europa",
    price_eur: 39, savings_pct: 56, savings_eur: 50, nights: 3,
    date_out: "2026-11-06", date_ret: "2026-11-09",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Ryanair",
    stops: 0, duration_min: 175, score: 89 },
  { _key: "nov-eze", type: "flight", headline: "Frankfurt → Buenos Aires con Lufthansa desde 695€",
    origin: "FRA", destination: "EZE", city_from: "Fráncfort", city_to: "Buenos Aires",
    country_to: "Argentina", region: "América Sur",
    price_eur: 695, savings_pct: 32, savings_eur: 325, nights: 14,
    date_out: "2026-11-12", date_ret: "2026-11-26",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Lufthansa",
    stops: 0, duration_min: 815, score: 70 },
  { _key: "nov-puj", type: "flight", headline: "Madrid → Punta Cana con Air Europa desde 525€",
    origin: "MAD", destination: "PUJ", city_from: "Madrid", city_to: "Punta Cana",
    country_to: "República Dominicana", region: "Caribe",
    price_eur: 525, savings_pct: 38, savings_eur: 320, nights: 7,
    date_out: "2026-11-15", date_ret: "2026-11-22",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Air Europa",
    stops: 0, duration_min: 575, score: 78 },
  { _key: "nov-hnd-business", type: "flight", headline: "Frankfurt → Tokio business con ANA desde 1.895€",
    origin: "FRA", destination: "HND", city_from: "Fráncfort", city_to: "Tokio",
    country_to: "Japón", region: "Asia",
    price_eur: 1895, savings_pct: 49, savings_eur: 1815, nights: 10,
    date_out: "2026-11-08", date_ret: "2026-11-18",
    classification: "CRÍTICO", cabin: "business",
    airline_name: "ANA",
    stops: 0, duration_min: 720, score: 93 },

  // DIC 2026
  { _key: "dic-ber", type: "flight", headline: "Madrid → Berlín con easyJet desde 65€",
    origin: "MAD", destination: "BER", city_from: "Madrid", city_to: "Berlín",
    country_to: "Alemania", region: "Europa",
    price_eur: 65, savings_pct: 47, savings_eur: 58, nights: 4,
    date_out: "2026-12-04", date_ret: "2026-12-08",
    classification: "OFERTA", cabin: "economy",
    airline_name: "easyJet",
    stops: 0, duration_min: 210, score: 86 },
  { _key: "dic-cun", type: "flight", headline: "Barcelona → Cancún con Aeroméxico desde 645€",
    origin: "BCN", destination: "CUN", city_from: "Barcelona", city_to: "Cancún",
    country_to: "México", region: "Caribe",
    price_eur: 645, savings_pct: 31, savings_eur: 295, nights: 8,
    date_out: "2026-12-15", date_ret: "2026-12-23",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Aeroméxico",
    stops: 1, duration_min: 720, score: 75 },
  { _key: "dic-hkg-error", type: "flight", headline: "Madrid → Hong Kong con Cathay error fare 395€",
    origin: "MAD", destination: "HKG", city_from: "Madrid", city_to: "Hong Kong",
    country_to: "Hong Kong", region: "Asia",
    price_eur: 395, savings_pct: 71, savings_eur: 980, nights: 10,
    date_out: "2026-12-12", date_ret: "2026-12-22",
    classification: "ERROR", cabin: "economy",
    airline_name: "Cathay Pacific",
    stops: 1, duration_min: 880, score: 99 },

  // ENE 2027
  { _key: "ene-hav", type: "flight", headline: "Madrid → La Habana con Air Europa desde 489€",
    origin: "MAD", destination: "HAV", city_from: "Madrid", city_to: "La Habana",
    country_to: "Cuba", region: "Caribe",
    price_eur: 489, savings_pct: 42, savings_eur: 354, nights: 9,
    date_out: "2027-01-12", date_ret: "2027-01-21",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Air Europa",
    stops: 0, duration_min: 555, score: 79 },
  { _key: "ene-sgn", type: "flight", headline: "Barcelona → Saigón con Vietnam Airlines desde 545€",
    origin: "BCN", destination: "SGN", city_from: "Barcelona", city_to: "Saigón",
    country_to: "Vietnam", region: "Asia",
    price_eur: 545, savings_pct: 38, savings_eur: 335, nights: 14,
    date_out: "2027-01-18", date_ret: "2027-02-01",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Vietnam Airlines",
    stops: 1, duration_min: 905, score: 76 },

  // FEB 2027
  { _key: "feb-vce", type: "flight", headline: "Madrid → Venecia carnaval con Vueling desde 145€",
    origin: "MAD", destination: "VCE", city_from: "Madrid", city_to: "Venecia",
    country_to: "Italia", region: "Europa",
    price_eur: 145, savings_pct: 36, savings_eur: 82, nights: 4,
    date_out: "2027-02-13", date_ret: "2027-02-17",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Vueling",
    stops: 0, duration_min: 165, score: 74 },
  { _key: "feb-ssh", type: "flight", headline: "Madrid → Sharm El Sheikh con TUI desde 365€",
    origin: "MAD", destination: "SSH", city_from: "Madrid", city_to: "Sharm El Sheikh",
    country_to: "Egipto", region: "Oriente Medio",
    price_eur: 365, savings_pct: 35, savings_eur: 195, nights: 7,
    date_out: "2027-02-20", date_ret: "2027-02-27",
    classification: "OFERTA", cabin: "economy",
    airline_name: "TUI fly",
    stops: 1, duration_min: 320, score: 72 },
  { _key: "feb-dxb", type: "flight", headline: "Barcelona → Dubái premium con Emirates desde 985€",
    origin: "BCN", destination: "DXB", city_from: "Barcelona", city_to: "Dubái",
    country_to: "EAU", region: "Oriente Medio",
    price_eur: 985, savings_pct: 44, savings_eur: 765, nights: 6,
    date_out: "2027-02-01", date_ret: "2027-02-07",
    classification: "OFERTA", cabin: "premium_economy",
    airline_name: "Emirates",
    stops: 0, duration_min: 425, score: 81 },

  // MAR 2027
  { _key: "mar-fco", type: "flight", headline: "Barcelona → Roma con Ryanair desde 29€",
    origin: "BCN", destination: "FCO", city_from: "Barcelona", city_to: "Roma",
    country_to: "Italia", region: "Europa",
    price_eur: 29, savings_pct: 64, savings_eur: 51, nights: 3,
    date_out: "2027-03-12", date_ret: "2027-03-15",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Ryanair",
    stops: 0, duration_min: 130, score: 92 },
  { _key: "mar-kix", type: "flight", headline: "Madrid → Osaka cherry blossom con Iberia desde 745€",
    origin: "MAD", destination: "KIX", city_from: "Madrid", city_to: "Osaka",
    country_to: "Japón", region: "Asia",
    price_eur: 745, savings_pct: 28, savings_eur: 295, nights: 12,
    date_out: "2027-03-22", date_ret: "2027-04-03",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Iberia",
    stops: 1, duration_min: 935, score: 70 },

  // ABR 2027
  { _key: "abr-ath", type: "flight", headline: "Madrid → Atenas con Aegean desde 125€",
    origin: "MAD", destination: "ATH", city_from: "Madrid", city_to: "Atenas",
    country_to: "Grecia", region: "Europa",
    price_eur: 125, savings_pct: 38, savings_eur: 78, nights: 5,
    date_out: "2027-04-09", date_ret: "2027-04-14",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Aegean Airlines",
    stops: 0, duration_min: 210, score: 78 },
  { _key: "abr-cpt", type: "flight", headline: "Frankfurt → Cape Town con Lufthansa desde 595€",
    origin: "FRA", destination: "CPT", city_from: "Fráncfort", city_to: "Cape Town",
    country_to: "Sudáfrica", region: "África",
    price_eur: 595, savings_pct: 41, savings_eur: 415, nights: 11,
    date_out: "2027-04-15", date_ret: "2027-04-26",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Lufthansa",
    stops: 0, duration_min: 720, score: 79 },

  // MAY 2027
  { _key: "may-ams", type: "flight", headline: "Madrid → Ámsterdam con KLM desde 105€",
    origin: "MAD", destination: "AMS", city_from: "Madrid", city_to: "Ámsterdam",
    country_to: "Países Bajos", region: "Europa",
    price_eur: 105, savings_pct: 32, savings_eur: 50, nights: 4,
    date_out: "2027-05-08", date_ret: "2027-05-12",
    classification: "OFERTA", cabin: "economy",
    airline_name: "KLM",
    stops: 0, duration_min: 175, score: 73 },
  { _key: "may-jmk", type: "flight", headline: "Barcelona → Mykonos con easyJet desde 89€",
    origin: "BCN", destination: "JMK", city_from: "Barcelona", city_to: "Mykonos",
    country_to: "Grecia", region: "Europa",
    price_eur: 89, savings_pct: 45, savings_eur: 73, nights: 5,
    date_out: "2027-05-15", date_ret: "2027-05-20",
    classification: "OFERTA", cabin: "economy",
    airline_name: "easyJet",
    stops: 0, duration_min: 215, score: 84 },

  // JUN 2027 (sustituye los viejos jun-2026)
  { _key: "jun-dub", type: "flight", headline: "Madrid → Dublín con Ryanair desde 45€",
    origin: "MAD", destination: "DUB", city_from: "Madrid", city_to: "Dublín",
    country_to: "Irlanda", region: "Europa",
    price_eur: 45, savings_pct: 50, savings_eur: 45, nights: 3,
    date_out: "2027-06-04", date_ret: "2027-06-07",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Ryanair",
    stops: 0, duration_min: 175, score: 90 },
  { _key: "jun-sin", type: "flight", headline: "Barcelona → Singapur con Singapore Airlines desde 695€",
    origin: "BCN", destination: "SIN", city_from: "Barcelona", city_to: "Singapur",
    country_to: "Singapur", region: "Asia",
    price_eur: 695, savings_pct: 35, savings_eur: 375, nights: 10,
    date_out: "2027-06-14", date_ret: "2027-06-24",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Singapore Airlines",
    stops: 1, duration_min: 920, score: 76 },

  // ── F3 fase ii: +20 deals adicionales (60 total) — más rutas + variedad ─

  // USA & Canadá (sub-representado antes)
  { _key: "ago-jfk-economy", type: "flight", headline: "Madrid → Nueva York con Iberia desde 425€",
    origin: "MAD", destination: "JFK", city_from: "Madrid", city_to: "Nueva York",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 425, savings_pct: 38, savings_eur: 265, nights: 7,
    date_out: "2026-08-22", date_ret: "2026-08-29",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Iberia",
    stops: 0, duration_min: 510, score: 78 },
  { _key: "oct-yyz", type: "flight", headline: "Madrid → Toronto con Air Canada desde 525€",
    origin: "MAD", destination: "YYZ", city_from: "Madrid", city_to: "Toronto",
    country_to: "Canadá", region: "América Norte",
    price_eur: 525, savings_pct: 32, savings_eur: 250, nights: 8,
    date_out: "2026-10-08", date_ret: "2026-10-16",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Air Canada",
    stops: 0, duration_min: 545, score: 75 },
  { _key: "feb-mia", type: "flight", headline: "Madrid → Miami con Iberia desde 495€",
    origin: "MAD", destination: "MIA", city_from: "Madrid", city_to: "Miami",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 495, savings_pct: 35, savings_eur: 265, nights: 9,
    date_out: "2027-02-14", date_ret: "2027-02-23",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Iberia",
    stops: 0, duration_min: 595, score: 76 },
  { _key: "abr-lax", type: "flight", headline: "Madrid → Los Ángeles con Iberia desde 595€",
    origin: "MAD", destination: "LAX", city_from: "Madrid", city_to: "Los Ángeles",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 595, savings_pct: 31, savings_eur: 265, nights: 10,
    date_out: "2027-04-22", date_ret: "2027-05-02",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Iberia",
    stops: 0, duration_min: 740, score: 74 },

  // Sudamérica (más allá de EZE/HAV)
  { _key: "sep-gru", type: "flight", headline: "Madrid → São Paulo con LATAM desde 595€",
    origin: "MAD", destination: "GRU", city_from: "Madrid", city_to: "São Paulo",
    country_to: "Brasil", region: "América Sur",
    price_eur: 595, savings_pct: 36, savings_eur: 335, nights: 14,
    date_out: "2026-09-08", date_ret: "2026-09-22",
    classification: "OFERTA", cabin: "economy",
    airline_name: "LATAM",
    stops: 0, duration_min: 685, score: 76 },
  { _key: "oct-lim", type: "flight", headline: "Madrid → Lima con Air Europa desde 645€",
    origin: "MAD", destination: "LIM", city_from: "Madrid", city_to: "Lima",
    country_to: "Perú", region: "América Sur",
    price_eur: 645, savings_pct: 32, savings_eur: 305, nights: 12,
    date_out: "2026-10-05", date_ret: "2026-10-17",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Air Europa",
    stops: 0, duration_min: 715, score: 74 },
  { _key: "abr-bog", type: "flight", headline: "Madrid → Bogotá con Avianca desde 525€",
    origin: "MAD", destination: "BOG", city_from: "Madrid", city_to: "Bogotá",
    country_to: "Colombia", region: "América Sur",
    price_eur: 525, savings_pct: 35, savings_eur: 280, nights: 11,
    date_out: "2027-04-10", date_ret: "2027-04-21",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Avianca",
    stops: 0, duration_min: 640, score: 76 },

  // Europa Sur extra
  { _key: "sep-bcn-bud", type: "flight", headline: "Barcelona → Budapest con Ryanair desde 49€",
    origin: "BCN", destination: "BUD", city_from: "Barcelona", city_to: "Budapest",
    country_to: "Hungría", region: "Europa",
    price_eur: 49, savings_pct: 51, savings_eur: 51, nights: 4,
    date_out: "2026-09-18", date_ret: "2026-09-22",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Ryanair",
    stops: 0, duration_min: 165, score: 88 },
  { _key: "oct-mad-dbv", type: "flight", headline: "Madrid → Dubrovnik con Vueling desde 95€",
    origin: "MAD", destination: "DBV", city_from: "Madrid", city_to: "Dubrovnik",
    country_to: "Croacia", region: "Europa",
    price_eur: 95, savings_pct: 42, savings_eur: 70, nights: 4,
    date_out: "2026-10-02", date_ret: "2026-10-06",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Vueling",
    stops: 0, duration_min: 215, score: 79 },
  { _key: "may-bcn-mad-fnc", type: "flight", headline: "Madrid → Funchal (Madeira) con TAP desde 145€",
    origin: "MAD", destination: "FNC", city_from: "Madrid", city_to: "Funchal",
    country_to: "Portugal", region: "Europa",
    price_eur: 145, savings_pct: 32, savings_eur: 70, nights: 5,
    date_out: "2027-05-10", date_ret: "2027-05-15",
    classification: "OFERTA", cabin: "economy",
    airline_name: "TAP Portugal",
    stops: 1, duration_min: 215, score: 73 },

  // Asia ampliado
  { _key: "nov-bcn-pek", type: "flight", headline: "Barcelona → Pekín con Air China desde 525€",
    origin: "BCN", destination: "PEK", city_from: "Barcelona", city_to: "Pekín",
    country_to: "China", region: "Asia",
    price_eur: 525, savings_pct: 35, savings_eur: 285, nights: 10,
    date_out: "2026-11-04", date_ret: "2026-11-14",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Air China",
    stops: 1, duration_min: 875, score: 75 },
  { _key: "ene-mad-icn", type: "flight", headline: "Madrid → Seúl con Korean Air desde 695€",
    origin: "MAD", destination: "ICN", city_from: "Madrid", city_to: "Seúl",
    country_to: "Corea del Sur", region: "Asia",
    price_eur: 695, savings_pct: 30, savings_eur: 295, nights: 11,
    date_out: "2027-01-22", date_ret: "2027-02-02",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Korean Air",
    stops: 1, duration_min: 920, score: 76 },
  { _key: "abr-bcn-del", type: "flight", headline: "Barcelona → Delhi con Air India desde 545€",
    origin: "BCN", destination: "DEL", city_from: "Barcelona", city_to: "Delhi",
    country_to: "India", region: "Asia",
    price_eur: 545, savings_pct: 38, savings_eur: 335, nights: 14,
    date_out: "2027-04-08", date_ret: "2027-04-22",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Air India",
    stops: 1, duration_min: 855, score: 75 },

  // África ampliado
  { _key: "ago-mad-rba", type: "flight", headline: "Madrid → Rabat con Royal Air Maroc desde 105€",
    origin: "MAD", destination: "RBA", city_from: "Madrid", city_to: "Rabat",
    country_to: "Marruecos", region: "África",
    price_eur: 105, savings_pct: 35, savings_eur: 55, nights: 4,
    date_out: "2026-08-04", date_ret: "2026-08-08",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Royal Air Maroc",
    stops: 0, duration_min: 165, score: 76 },
  { _key: "oct-bcn-tnr", type: "flight", headline: "Barcelona → Antananarivo con Air France desde 845€",
    origin: "BCN", destination: "TNR", city_from: "Barcelona", city_to: "Antananarivo",
    country_to: "Madagascar", region: "África",
    price_eur: 845, savings_pct: 28, savings_eur: 325, nights: 14,
    date_out: "2026-10-15", date_ret: "2026-10-29",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Air France",
    stops: 1, duration_min: 1020, score: 74 },

  // Oriente Medio
  { _key: "feb-mad-amm", type: "flight", headline: "Madrid → Ammán con Royal Jordanian desde 365€",
    origin: "MAD", destination: "AMM", city_from: "Madrid", city_to: "Ammán",
    country_to: "Jordania", region: "Oriente Medio",
    price_eur: 365, savings_pct: 35, savings_eur: 195, nights: 8,
    date_out: "2027-02-08", date_ret: "2027-02-16",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Royal Jordanian",
    stops: 1, duration_min: 425, score: 75 },
  { _key: "mar-bcn-tlv", type: "flight", headline: "Barcelona → Tel Aviv con El Al desde 295€",
    origin: "BCN", destination: "TLV", city_from: "Barcelona", city_to: "Tel Aviv",
    country_to: "Israel", region: "Oriente Medio",
    price_eur: 295, savings_pct: 30, savings_eur: 125, nights: 6,
    date_out: "2027-03-08", date_ret: "2027-03-14",
    classification: "OFERTA", cabin: "economy",
    airline_name: "El Al",
    stops: 0, duration_min: 285, score: 73 },

  // Oceanía + Pacífico
  { _key: "ene-mad-akl", type: "flight", headline: "Madrid → Auckland con Qatar Airways desde 1095€",
    origin: "MAD", destination: "AKL", city_from: "Madrid", city_to: "Auckland",
    country_to: "Nueva Zelanda", region: "Oceanía",
    price_eur: 1095, savings_pct: 33, savings_eur: 545, nights: 14,
    date_out: "2027-01-08", date_ret: "2027-01-22",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Qatar Airways",
    stops: 1, duration_min: 1820, score: 75 },
  { _key: "abr-mad-ppt", type: "flight", headline: "Madrid → Tahití con Air France desde 1395€",
    origin: "MAD", destination: "PPT", city_from: "Madrid", city_to: "Papeete",
    country_to: "Polinesia Francesa", region: "Oceanía",
    price_eur: 1395, savings_pct: 28, savings_eur: 545, nights: 14,
    date_out: "2027-04-15", date_ret: "2027-04-29",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Air France",
    stops: 1, duration_min: 1420, score: 73 },

  // Hoteles extras
  { _key: "hotel-cun", type: "hotel", headline: "Hotel Cancún 4★ Hotel Zone 7 noches 595€",
    origin: "—", destination: "CUN", city_from: "—", city_to: "Cancún",
    country_to: "México", region: "Caribe",
    price_eur: 595, savings_pct: 30, savings_eur: 250, nights: 7,
    date_out: "2026-12-15", date_ret: "2026-12-22",
    classification: "OFERTA", cabin: "economy",
    airline_name: "Hotel",
    stops: 0, duration_min: 0, score: 70 },

  // fase ss-SS7: +20 deals diversos para mejor cobertura cuando worker falla
  // Cubre rutas adicionales en MAY/JUN/SEP/NOV evitando huecos en calendario
  { _key: "may-cph", type: "flight", headline: "Madrid → Copenhague con SAS desde 109€",
    origin: "MAD", destination: "CPH", city_from: "Madrid", city_to: "Copenhague",
    country_to: "Dinamarca", region: "Europa",
    price_eur: 109, savings_pct: 38, savings_eur: 67, nights: 4,
    date_out: "2026-05-15", date_ret: "2026-05-19",
    classification: "OFERTA", cabin: "economy", airline_name: "SAS",
    stops: 0, duration_min: 230, score: 79 },
  { _key: "may-vno", type: "flight", headline: "Barcelona → Vilna con Wizz desde 39€",
    origin: "BCN", destination: "VNO", city_from: "Barcelona", city_to: "Vilna",
    country_to: "Lituania", region: "Europa",
    price_eur: 39, savings_pct: 52, savings_eur: 42, nights: 3,
    date_out: "2026-05-22", date_ret: "2026-05-25",
    classification: "OFERTA", cabin: "economy", airline_name: "Wizz Air",
    stops: 0, duration_min: 235, score: 81 },
  { _key: "may-tia", type: "flight", headline: "Madrid → Tirana con Wizz desde 45€",
    origin: "MAD", destination: "TIA", city_from: "Madrid", city_to: "Tirana",
    country_to: "Albania", region: "Balcanes",
    price_eur: 45, savings_pct: 49, savings_eur: 43, nights: 4,
    date_out: "2026-05-08", date_ret: "2026-05-12",
    classification: "OFERTA", cabin: "economy", airline_name: "Wizz Air",
    stops: 0, duration_min: 195, score: 78 },
  { _key: "jun-tlv", type: "flight", headline: "Madrid → Tel Aviv con El Al desde 195€",
    origin: "MAD", destination: "TLV", city_from: "Madrid", city_to: "Tel Aviv",
    country_to: "Israel", region: "Mediterráneo Este",
    price_eur: 195, savings_pct: 41, savings_eur: 135, nights: 5,
    date_out: "2026-06-12", date_ret: "2026-06-17",
    classification: "OFERTA", cabin: "economy", airline_name: "El Al",
    stops: 0, duration_min: 240, score: 73 },
  { _key: "jun-bey", type: "flight", headline: "Barcelona → Beirut con Vueling desde 165€",
    origin: "BCN", destination: "BEY", city_from: "Barcelona", city_to: "Beirut",
    country_to: "Líbano", region: "Mediterráneo Este",
    price_eur: 165, savings_pct: 44, savings_eur: 130, nights: 5,
    date_out: "2026-06-19", date_ret: "2026-06-24",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 215, score: 71 },
  { _key: "sep-svo", type: "flight", headline: "Madrid → Moscú con Turkish desde 245€",
    origin: "MAD", destination: "SVO", city_from: "Madrid", city_to: "Moscú",
    country_to: "Rusia", region: "Europa",
    price_eur: 245, savings_pct: 35, savings_eur: 132, nights: 5,
    date_out: "2026-09-04", date_ret: "2026-09-09",
    classification: "OFERTA", cabin: "economy", airline_name: "Turkish Airlines",
    stops: 1, duration_min: 360, score: 65 },
  { _key: "sep-otp", type: "flight", headline: "Barcelona → Bucarest con Wizz desde 49€",
    origin: "BCN", destination: "OTP", city_from: "Barcelona", city_to: "Bucarest",
    country_to: "Rumanía", region: "Europa",
    price_eur: 49, savings_pct: 50, savings_eur: 49, nights: 4,
    date_out: "2026-09-11", date_ret: "2026-09-15",
    classification: "OFERTA", cabin: "economy", airline_name: "Wizz Air",
    stops: 0, duration_min: 200, score: 80 },
  { _key: "sep-sof", type: "flight", headline: "Madrid → Sofía con Wizz desde 55€",
    origin: "MAD", destination: "SOF", city_from: "Madrid", city_to: "Sofía",
    country_to: "Bulgaria", region: "Europa",
    price_eur: 55, savings_pct: 47, savings_eur: 49, nights: 4,
    date_out: "2026-09-18", date_ret: "2026-09-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Wizz Air",
    stops: 0, duration_min: 200, score: 79 },
  { _key: "sep-zag", type: "flight", headline: "Barcelona → Zagreb con Croatia desde 89€",
    origin: "BCN", destination: "ZAG", city_from: "Barcelona", city_to: "Zagreb",
    country_to: "Croacia", region: "Europa",
    price_eur: 89, savings_pct: 38, savings_eur: 55, nights: 3,
    date_out: "2026-09-25", date_ret: "2026-09-28",
    classification: "OFERTA", cabin: "economy", airline_name: "Croatia Airlines",
    stops: 0, duration_min: 175, score: 73 },
  { _key: "nov-cai", type: "flight", headline: "Madrid → El Cairo con EgyptAir desde 215€",
    origin: "MAD", destination: "CAI", city_from: "Madrid", city_to: "El Cairo",
    country_to: "Egipto", region: "África Norte",
    price_eur: 215, savings_pct: 39, savings_eur: 137, nights: 6,
    date_out: "2026-11-07", date_ret: "2026-11-13",
    classification: "OFERTA", cabin: "economy", airline_name: "EgyptAir",
    stops: 0, duration_min: 250, score: 76 },
  { _key: "nov-amm", type: "flight", headline: "Barcelona → Amán con Royal Jordanian desde 245€",
    origin: "BCN", destination: "AMM", city_from: "Barcelona", city_to: "Amán",
    country_to: "Jordania", region: "Mediterráneo Este",
    price_eur: 245, savings_pct: 36, savings_eur: 138, nights: 7,
    date_out: "2026-11-14", date_ret: "2026-11-21",
    classification: "OFERTA", cabin: "economy", airline_name: "Royal Jordanian",
    stops: 0, duration_min: 270, score: 74 },
  { _key: "nov-rak", type: "flight", headline: "Madrid → Marrakech con Ryanair desde 49€",
    origin: "MAD", destination: "RAK", city_from: "Madrid", city_to: "Marrakech",
    country_to: "Marruecos", region: "África Norte",
    price_eur: 49, savings_pct: 51, savings_eur: 51, nights: 4,
    date_out: "2026-11-21", date_ret: "2026-11-25",
    classification: "OFERTA", cabin: "economy", airline_name: "Ryanair",
    stops: 0, duration_min: 175, score: 84 },
  { _key: "dic-amm-2", type: "flight", headline: "Madrid → Praga con Vueling desde 75€",
    origin: "MAD", destination: "PRG", city_from: "Madrid", city_to: "Praga",
    country_to: "Chequia", region: "Europa",
    price_eur: 75, savings_pct: 45, savings_eur: 62, nights: 3,
    date_out: "2026-12-05", date_ret: "2026-12-08",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 175, score: 82 },
  { _key: "ene-cur", type: "flight", headline: "Madrid → Curaçao con KLM desde 425€",
    origin: "MAD", destination: "CUR", city_from: "Madrid", city_to: "Curaçao",
    country_to: "Curazao", region: "Caribe",
    price_eur: 425, savings_pct: 41, savings_eur: 295, nights: 9,
    date_out: "2027-01-08", date_ret: "2027-01-17",
    classification: "OFERTA", cabin: "economy", airline_name: "KLM",
    stops: 1, duration_min: 720, score: 81 },
  { _key: "ene-pty", type: "flight", headline: "Barcelona → Panamá con Copa desde 525€",
    origin: "BCN", destination: "PTY", city_from: "Barcelona", city_to: "Panamá",
    country_to: "Panamá", region: "Centroamérica",
    price_eur: 525, savings_pct: 33, savings_eur: 255, nights: 8,
    date_out: "2027-01-15", date_ret: "2027-01-23",
    classification: "OFERTA", cabin: "economy", airline_name: "Copa Airlines",
    stops: 0, duration_min: 660, score: 78 },
  { _key: "feb-jed", type: "flight", headline: "Madrid → Yeda con Saudia desde 395€",
    origin: "MAD", destination: "JED", city_from: "Madrid", city_to: "Yeda",
    country_to: "Arabia Saudí", region: "Oriente Medio",
    price_eur: 395, savings_pct: 38, savings_eur: 245, nights: 5,
    date_out: "2027-02-05", date_ret: "2027-02-10",
    classification: "OFERTA", cabin: "economy", airline_name: "Saudia",
    stops: 0, duration_min: 380, score: 70 },
  { _key: "mar-mle-2", type: "flight", headline: "Madrid → Maldivas con Etihad business desde 1495€",
    origin: "MAD", destination: "MLE", city_from: "Madrid", city_to: "Malé",
    country_to: "Maldivas", region: "Asia Sur",
    price_eur: 1495, savings_pct: 55, savings_eur: 1830, nights: 7,
    date_out: "2027-03-12", date_ret: "2027-03-19",
    classification: "ERROR", cabin: "business", airline_name: "Etihad",
    stops: 1, duration_min: 720, score: 95 },
  { _key: "abr-pun", type: "flight", headline: "Barcelona → Punta Cana con Iberia desde 565€",
    origin: "BCN", destination: "PUJ", city_from: "Barcelona", city_to: "Punta Cana",
    country_to: "República Dominicana", region: "Caribe",
    price_eur: 565, savings_pct: 35, savings_eur: 305, nights: 9,
    date_out: "2027-04-09", date_ret: "2027-04-18",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 0, duration_min: 600, score: 79 },
  { _key: "may-tlv-2", type: "flight", headline: "Madrid → Mauricio con Air France desde 695€",
    origin: "MAD", destination: "MRU", city_from: "Madrid", city_to: "Mauricio",
    country_to: "Mauricio", region: "África",
    price_eur: 695, savings_pct: 40, savings_eur: 460, nights: 8,
    date_out: "2027-05-14", date_ret: "2027-05-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Air France",
    stops: 1, duration_min: 750, score: 78 },
  { _key: "jun-cgk", type: "flight", headline: "Madrid → Yakarta con Qatar desde 685€",
    origin: "MAD", destination: "CGK", city_from: "Madrid", city_to: "Yakarta",
    country_to: "Indonesia", region: "Sudeste Asiático",
    price_eur: 685, savings_pct: 39, savings_eur: 435, nights: 12,
    date_out: "2027-06-04", date_ret: "2027-06-16",
    classification: "OFERTA", cabin: "economy", airline_name: "Qatar Airways",
    stops: 1, duration_min: 920, score: 77 },

  // ─── HHH3 (Apr 2026) — expansion 80+ rutas adicionales para corto plazo ───
  // Incluye más orígenes (PMI/AGP/SVQ/BIO/VLC/MUC/FRA/AMS/CDG), más destinos
  // (LATAM, África, Asia oriental, Europa Este), más spread fechas mismo mes.

  // ── MAY 2026 — corto plazo, alta demanda
  { _key: "may-pmi-ham", type: "flight", headline: "Palma → Hamburgo con Eurowings desde 49€",
    origin: "PMI", destination: "HAM", city_from: "Palma de Mallorca", city_to: "Hamburgo",
    country_to: "Alemania", region: "Europa",
    price_eur: 49, savings_pct: 40, savings_eur: 33, nights: 3,
    date_out: "2026-05-22", date_ret: "2026-05-25",
    classification: "OFERTA", cabin: "economy", airline_name: "Eurowings",
    stops: 0, duration_min: 190, score: 71 },
  { _key: "may-agp-zrh", type: "flight", headline: "Málaga → Zúrich con Swiss desde 89€",
    origin: "AGP", destination: "ZRH", city_from: "Málaga", city_to: "Zúrich",
    country_to: "Suiza", region: "Europa",
    price_eur: 89, savings_pct: 41, savings_eur: 62, nights: 5,
    date_out: "2026-05-15", date_ret: "2026-05-20",
    classification: "OFERTA", cabin: "economy", airline_name: "Swiss",
    stops: 0, duration_min: 200, score: 78 },
  { _key: "may-bio-vie", type: "flight", headline: "Bilbao → Viena con Ryanair desde 39€",
    origin: "BIO", destination: "VIE", city_from: "Bilbao", city_to: "Viena",
    country_to: "Austria", region: "Europa",
    price_eur: 39, savings_pct: 50, savings_eur: 39, nights: 4,
    date_out: "2026-05-09", date_ret: "2026-05-13",
    classification: "OFERTA", cabin: "economy", airline_name: "Ryanair",
    stops: 0, duration_min: 195, score: 79 },
  { _key: "may-svq-prg", type: "flight", headline: "Sevilla → Praga con Ryanair desde 35€",
    origin: "SVQ", destination: "PRG", city_from: "Sevilla", city_to: "Praga",
    country_to: "Chequia", region: "Europa",
    price_eur: 35, savings_pct: 53, savings_eur: 39, nights: 4,
    date_out: "2026-05-23", date_ret: "2026-05-27",
    classification: "OFERTA", cabin: "economy", airline_name: "Ryanair",
    stops: 0, duration_min: 200, score: 80 },
  { _key: "may-mad-pmi", type: "flight", headline: "Madrid → Palma con Vueling desde 28€",
    origin: "MAD", destination: "PMI", city_from: "Madrid", city_to: "Palma de Mallorca",
    country_to: "España", region: "Europa",
    price_eur: 28, savings_pct: 38, savings_eur: 17, nights: 3,
    date_out: "2026-05-29", date_ret: "2026-06-01",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 80, score: 73 },
  { _key: "may-bcn-ath-2", type: "flight", headline: "Barcelona → Atenas con Aegean desde 79€",
    origin: "BCN", destination: "ATH", city_from: "Barcelona", city_to: "Atenas",
    country_to: "Grecia", region: "Europa",
    price_eur: 79, savings_pct: 47, savings_eur: 71, nights: 5,
    date_out: "2026-05-12", date_ret: "2026-05-17",
    classification: "OFERTA", cabin: "economy", airline_name: "Aegean",
    stops: 0, duration_min: 195, score: 82 },
  { _key: "may-mad-cdg-2", type: "flight", headline: "Madrid → París con Air France desde 65€",
    origin: "MAD", destination: "CDG", city_from: "Madrid", city_to: "París",
    country_to: "Francia", region: "Europa",
    price_eur: 65, savings_pct: 48, savings_eur: 60, nights: 4,
    date_out: "2026-05-08", date_ret: "2026-05-12",
    classification: "OFERTA", cabin: "economy", airline_name: "Air France",
    stops: 0, duration_min: 130, score: 76 },
  { _key: "may-bcn-fco", type: "flight", headline: "Barcelona → Roma con Vueling desde 49€",
    origin: "BCN", destination: "FCO", city_from: "Barcelona", city_to: "Roma",
    country_to: "Italia", region: "Europa",
    price_eur: 49, savings_pct: 51, savings_eur: 51, nights: 3,
    date_out: "2026-05-14", date_ret: "2026-05-17",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 145, score: 78 },

  // ── JUN 2026 — verano arranca, escapadas Europa
  { _key: "jun-agp-cph", type: "flight", headline: "Málaga → Copenhague con Norwegian desde 95€",
    origin: "AGP", destination: "CPH", city_from: "Málaga", city_to: "Copenhague",
    country_to: "Dinamarca", region: "Europa",
    price_eur: 95, savings_pct: 45, savings_eur: 78, nights: 5,
    date_out: "2026-06-10", date_ret: "2026-06-15",
    classification: "OFERTA", cabin: "economy", airline_name: "Norwegian",
    stops: 0, duration_min: 235, score: 79 },
  { _key: "jun-vlc-bcn-2", type: "flight", headline: "Valencia → Berlín con Wizz desde 59€",
    origin: "VLC", destination: "BER", city_from: "Valencia", city_to: "Berlín",
    country_to: "Alemania", region: "Europa",
    price_eur: 59, savings_pct: 47, savings_eur: 52, nights: 4,
    date_out: "2026-06-18", date_ret: "2026-06-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Wizz Air",
    stops: 0, duration_min: 195, score: 76 },
  { _key: "jun-mad-bos", type: "flight", headline: "Madrid → Boston con Iberia desde 380€",
    origin: "MAD", destination: "BOS", city_from: "Madrid", city_to: "Boston",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 380, savings_pct: 42, savings_eur: 275, nights: 7,
    date_out: "2026-06-04", date_ret: "2026-06-11",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 0, duration_min: 480, score: 84 },
  { _key: "jun-bcn-cmn", type: "flight", headline: "Barcelona → Casablanca con Royal Air Maroc desde 119€",
    origin: "BCN", destination: "CMN", city_from: "Barcelona", city_to: "Casablanca",
    country_to: "Marruecos", region: "África",
    price_eur: 119, savings_pct: 38, savings_eur: 73, nights: 5,
    date_out: "2026-06-23", date_ret: "2026-06-28",
    classification: "OFERTA", cabin: "economy", airline_name: "Royal Air Maroc",
    stops: 0, duration_min: 165, score: 75 },
  { _key: "jun-mad-tlv-2", type: "flight", headline: "Madrid → Tel Aviv con El Al desde 220€",
    origin: "MAD", destination: "TLV", city_from: "Madrid", city_to: "Tel Aviv",
    country_to: "Israel", region: "Oriente Medio",
    price_eur: 220, savings_pct: 41, savings_eur: 153, nights: 6,
    date_out: "2026-06-15", date_ret: "2026-06-21",
    classification: "OFERTA", cabin: "economy", airline_name: "El Al",
    stops: 0, duration_min: 270, score: 78 },
  { _key: "jun-mad-mex", type: "flight", headline: "Madrid → Ciudad de México con Aeroméxico desde 480€",
    origin: "MAD", destination: "MEX", city_from: "Madrid", city_to: "Ciudad de México",
    country_to: "México", region: "América Norte",
    price_eur: 480, savings_pct: 40, savings_eur: 320, nights: 10,
    date_out: "2026-06-12", date_ret: "2026-06-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Aeroméxico",
    stops: 0, duration_min: 660, score: 82 },
  { _key: "jun-bcn-mvd", type: "flight", headline: "Barcelona → Montevideo con LATAM desde 620€",
    origin: "BCN", destination: "MVD", city_from: "Barcelona", city_to: "Montevideo",
    country_to: "Uruguay", region: "América Sur",
    price_eur: 620, savings_pct: 36, savings_eur: 350, nights: 12,
    date_out: "2026-06-20", date_ret: "2026-07-02",
    classification: "OFERTA", cabin: "economy", airline_name: "LATAM",
    stops: 1, duration_min: 850, score: 79 },

  // ── JUL 2026 — pico verano, más opciones
  { _key: "jul-mad-pmo", type: "flight", headline: "Madrid → Palermo con Ryanair desde 65€",
    origin: "MAD", destination: "PMO", city_from: "Madrid", city_to: "Palermo",
    country_to: "Italia", region: "Europa",
    price_eur: 65, savings_pct: 50, savings_eur: 65, nights: 6,
    date_out: "2026-07-15", date_ret: "2026-07-21",
    classification: "OFERTA", cabin: "economy", airline_name: "Ryanair",
    stops: 0, duration_min: 165, score: 80 },
  { _key: "jul-bcn-spu", type: "flight", headline: "Barcelona → Split con easyJet desde 75€",
    origin: "BCN", destination: "SPU", city_from: "Barcelona", city_to: "Split",
    country_to: "Croacia", region: "Europa",
    price_eur: 75, savings_pct: 50, savings_eur: 75, nights: 7,
    date_out: "2026-07-08", date_ret: "2026-07-15",
    classification: "OFERTA", cabin: "economy", airline_name: "easyJet",
    stops: 0, duration_min: 165, score: 84 },
  { _key: "jul-mad-her", type: "flight", headline: "Madrid → Heraklion con Ryanair desde 95€",
    origin: "MAD", destination: "HER", city_from: "Madrid", city_to: "Heraklion",
    country_to: "Grecia", region: "Europa",
    price_eur: 95, savings_pct: 49, savings_eur: 91, nights: 7,
    date_out: "2026-07-19", date_ret: "2026-07-26",
    classification: "OFERTA", cabin: "economy", airline_name: "Ryanair",
    stops: 0, duration_min: 230, score: 83 },
  { _key: "jul-mad-jed", type: "flight", headline: "Madrid → Yeda con Saudia desde 380€",
    origin: "MAD", destination: "JED", city_from: "Madrid", city_to: "Yeda",
    country_to: "Arabia Saudita", region: "Oriente Medio",
    price_eur: 380, savings_pct: 47, savings_eur: 335, nights: 8,
    date_out: "2026-07-04", date_ret: "2026-07-12",
    classification: "OFERTA", cabin: "economy", airline_name: "Saudia",
    stops: 1, duration_min: 480, score: 76 },
  { _key: "jul-bcn-yyz", type: "flight", headline: "Barcelona → Toronto con Air Canada desde 420€",
    origin: "BCN", destination: "YYZ", city_from: "Barcelona", city_to: "Toronto",
    country_to: "Canadá", region: "América Norte",
    price_eur: 420, savings_pct: 47, savings_eur: 370, nights: 10,
    date_out: "2026-07-12", date_ret: "2026-07-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Air Canada",
    stops: 0, duration_min: 510, score: 84 },
  { _key: "jul-mad-zth-2", type: "flight", headline: "Madrid → Zante con Volotea desde 89€",
    origin: "MAD", destination: "ZTH", city_from: "Madrid", city_to: "Zante",
    country_to: "Grecia", region: "Europa",
    price_eur: 89, savings_pct: 46, savings_eur: 76, nights: 7,
    date_out: "2026-07-25", date_ret: "2026-08-01",
    classification: "OFERTA", cabin: "economy", airline_name: "Volotea",
    stops: 0, duration_min: 220, score: 78 },

  // ── AGO 2026 — corazón verano, business class deals
  { _key: "ago-mad-jfk-biz", type: "flight", headline: "Madrid → Nueva York Business con Iberia desde 1.490€",
    origin: "MAD", destination: "JFK", city_from: "Madrid", city_to: "Nueva York",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 1490, savings_pct: 53, savings_eur: 1680, nights: 7,
    date_out: "2026-08-15", date_ret: "2026-08-22",
    classification: "ERROR", cabin: "business", airline_name: "Iberia",
    stops: 0, duration_min: 480, score: 92 },
  { _key: "ago-mad-eze-biz", type: "flight", headline: "Madrid → Buenos Aires Business con Iberia desde 1.890€",
    origin: "MAD", destination: "EZE", city_from: "Madrid", city_to: "Buenos Aires",
    country_to: "Argentina", region: "América Sur",
    price_eur: 1890, savings_pct: 50, savings_eur: 1890, nights: 14,
    date_out: "2026-08-08", date_ret: "2026-08-22",
    classification: "ERROR", cabin: "business", airline_name: "Iberia",
    stops: 0, duration_min: 720, score: 91 },
  { _key: "ago-bcn-pmi", type: "flight", headline: "Barcelona → Palma con Vueling desde 32€",
    origin: "BCN", destination: "PMI", city_from: "Barcelona", city_to: "Palma de Mallorca",
    country_to: "España", region: "Europa",
    price_eur: 32, savings_pct: 35, savings_eur: 17, nights: 4,
    date_out: "2026-08-20", date_ret: "2026-08-24",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 60, score: 71 },
  { _key: "ago-mad-mle-biz", type: "flight", headline: "Madrid → Maldivas Business con Qatar desde 2.480€",
    origin: "MAD", destination: "MLE", city_from: "Madrid", city_to: "Maldivas",
    country_to: "Maldivas", region: "Asia",
    price_eur: 2480, savings_pct: 51, savings_eur: 2580, nights: 10,
    date_out: "2026-08-04", date_ret: "2026-08-14",
    classification: "ERROR", cabin: "business", airline_name: "Qatar Airways",
    stops: 1, duration_min: 870, score: 93 },
  { _key: "ago-bcn-rho", type: "flight", headline: "Barcelona → Rodas con Aegean desde 110€",
    origin: "BCN", destination: "RHO", city_from: "Barcelona", city_to: "Rodas",
    country_to: "Grecia", region: "Europa",
    price_eur: 110, savings_pct: 45, savings_eur: 90, nights: 7,
    date_out: "2026-08-12", date_ret: "2026-08-19",
    classification: "OFERTA", cabin: "economy", airline_name: "Aegean",
    stops: 0, duration_min: 230, score: 81 },

  // ── SEP 2026 — temporada baja arranca, gangas
  { _key: "sep-mad-cmn", type: "flight", headline: "Madrid → Casablanca con Ryanair desde 39€",
    origin: "MAD", destination: "CMN", city_from: "Madrid", city_to: "Casablanca",
    country_to: "Marruecos", region: "África",
    price_eur: 39, savings_pct: 60, savings_eur: 59, nights: 5,
    date_out: "2026-09-10", date_ret: "2026-09-15",
    classification: "OFERTA", cabin: "economy", airline_name: "Ryanair",
    stops: 0, duration_min: 175, score: 85 },
  { _key: "sep-bcn-vrn", type: "flight", headline: "Barcelona → Verona con Vueling desde 45€",
    origin: "BCN", destination: "VRN", city_from: "Barcelona", city_to: "Verona",
    country_to: "Italia", region: "Europa",
    price_eur: 45, savings_pct: 53, savings_eur: 51, nights: 4,
    date_out: "2026-09-18", date_ret: "2026-09-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 150, score: 80 },
  { _key: "sep-mad-cuz", type: "flight", headline: "Madrid → Cuzco con LATAM desde 580€",
    origin: "MAD", destination: "CUZ", city_from: "Madrid", city_to: "Cuzco",
    country_to: "Perú", region: "América Sur",
    price_eur: 580, savings_pct: 45, savings_eur: 480, nights: 12,
    date_out: "2026-09-04", date_ret: "2026-09-16",
    classification: "OFERTA", cabin: "economy", airline_name: "LATAM",
    stops: 1, duration_min: 870, score: 86 },
  { _key: "sep-mad-acc", type: "flight", headline: "Madrid → Accra con Air Maroc desde 320€",
    origin: "MAD", destination: "ACC", city_from: "Madrid", city_to: "Accra",
    country_to: "Ghana", region: "África",
    price_eur: 320, savings_pct: 48, savings_eur: 295, nights: 9,
    date_out: "2026-09-22", date_ret: "2026-10-01",
    classification: "OFERTA", cabin: "economy", airline_name: "Royal Air Maroc",
    stops: 1, duration_min: 540, score: 79 },
  { _key: "sep-bcn-tlv", type: "flight", headline: "Barcelona → Tel Aviv con Vueling desde 175€",
    origin: "BCN", destination: "TLV", city_from: "Barcelona", city_to: "Tel Aviv",
    country_to: "Israel", region: "Oriente Medio",
    price_eur: 175, savings_pct: 49, savings_eur: 168, nights: 6,
    date_out: "2026-09-13", date_ret: "2026-09-19",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 280, score: 80 },
  { _key: "sep-mad-icn", type: "flight", headline: "Madrid → Seúl con Korean Air desde 580€",
    origin: "MAD", destination: "ICN", city_from: "Madrid", city_to: "Seúl",
    country_to: "Corea del Sur", region: "Asia",
    price_eur: 580, savings_pct: 48, savings_eur: 535, nights: 10,
    date_out: "2026-09-08", date_ret: "2026-09-18",
    classification: "OFERTA", cabin: "economy", airline_name: "Korean Air",
    stops: 1, duration_min: 850, score: 84 },

  // ── OCT 2026 — temporada baja, error fares
  { _key: "oct-mad-hkg-biz", type: "flight", headline: "Madrid → Hong Kong Business con Cathay desde 1.890€",
    origin: "MAD", destination: "HKG", city_from: "Madrid", city_to: "Hong Kong",
    country_to: "Hong Kong", region: "Asia",
    price_eur: 1890, savings_pct: 56, savings_eur: 2390, nights: 10,
    date_out: "2026-10-12", date_ret: "2026-10-22",
    classification: "ERROR", cabin: "business", airline_name: "Cathay Pacific",
    stops: 0, duration_min: 800, score: 94 },
  { _key: "oct-bcn-bos", type: "flight", headline: "Barcelona → Boston con Level desde 280€",
    origin: "BCN", destination: "BOS", city_from: "Barcelona", city_to: "Boston",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 280, savings_pct: 47, savings_eur: 247, nights: 8,
    date_out: "2026-10-05", date_ret: "2026-10-13",
    classification: "OFERTA", cabin: "economy", airline_name: "Level",
    stops: 0, duration_min: 480, score: 86 },
  { _key: "oct-mad-yyz-2", type: "flight", headline: "Madrid → Toronto con Air Canada desde 320€",
    origin: "MAD", destination: "YYZ", city_from: "Madrid", city_to: "Toronto",
    country_to: "Canadá", region: "América Norte",
    price_eur: 320, savings_pct: 46, savings_eur: 273, nights: 9,
    date_out: "2026-10-18", date_ret: "2026-10-27",
    classification: "OFERTA", cabin: "economy", airline_name: "Air Canada",
    stops: 0, duration_min: 510, score: 84 },
  { _key: "oct-bcn-vie", type: "flight", headline: "Barcelona → Viena con Vueling desde 49€",
    origin: "BCN", destination: "VIE", city_from: "Barcelona", city_to: "Viena",
    country_to: "Austria", region: "Europa",
    price_eur: 49, savings_pct: 51, savings_eur: 51, nights: 4,
    date_out: "2026-10-22", date_ret: "2026-10-26",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 200, score: 78 },
  { _key: "oct-mad-amm", type: "flight", headline: "Madrid → Amán con Royal Jordanian desde 280€",
    origin: "MAD", destination: "AMM", city_from: "Madrid", city_to: "Amán",
    country_to: "Jordania", region: "Oriente Medio",
    price_eur: 280, savings_pct: 49, savings_eur: 270, nights: 8,
    date_out: "2026-10-08", date_ret: "2026-10-16",
    classification: "OFERTA", cabin: "economy", airline_name: "Royal Jordanian",
    stops: 0, duration_min: 320, score: 81 },
  { _key: "oct-mad-cpt", type: "flight", headline: "Madrid → Ciudad del Cabo con KLM desde 580€",
    origin: "MAD", destination: "CPT", city_from: "Madrid", city_to: "Ciudad del Cabo",
    country_to: "Sudáfrica", region: "África",
    price_eur: 580, savings_pct: 51, savings_eur: 605, nights: 12,
    date_out: "2026-10-15", date_ret: "2026-10-27",
    classification: "OFERTA", cabin: "economy", airline_name: "KLM",
    stops: 1, duration_min: 870, score: 88 },

  // ── NOV 2026 — Acción de gracias, pre-Navidad
  { _key: "nov-mad-mia-2", type: "flight", headline: "Madrid → Miami con Iberia desde 380€",
    origin: "MAD", destination: "MIA", city_from: "Madrid", city_to: "Miami",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 380, savings_pct: 47, savings_eur: 340, nights: 9,
    date_out: "2026-11-05", date_ret: "2026-11-14",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 0, duration_min: 580, score: 84 },
  { _key: "nov-mad-fco-2", type: "flight", headline: "Madrid → Roma con Iberia Express desde 49€",
    origin: "MAD", destination: "FCO", city_from: "Madrid", city_to: "Roma",
    country_to: "Italia", region: "Europa",
    price_eur: 49, savings_pct: 52, savings_eur: 53, nights: 4,
    date_out: "2026-11-15", date_ret: "2026-11-19",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia Express",
    stops: 0, duration_min: 165, score: 77 },
  { _key: "nov-bcn-ist", type: "flight", headline: "Barcelona → Estambul con Pegasus desde 99€",
    origin: "BCN", destination: "IST", city_from: "Barcelona", city_to: "Estambul",
    country_to: "Turquía", region: "Asia",
    price_eur: 99, savings_pct: 56, savings_eur: 126, nights: 6,
    date_out: "2026-11-23", date_ret: "2026-11-29",
    classification: "OFERTA", cabin: "economy", airline_name: "Pegasus",
    stops: 0, duration_min: 230, score: 82 },
  { _key: "nov-mad-cun-2", type: "flight", headline: "Madrid → Cancún con Air Europa desde 420€",
    origin: "MAD", destination: "CUN", city_from: "Madrid", city_to: "Cancún",
    country_to: "México", region: "Caribe",
    price_eur: 420, savings_pct: 47, savings_eur: 375, nights: 10,
    date_out: "2026-11-12", date_ret: "2026-11-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Air Europa",
    stops: 0, duration_min: 660, score: 87 },
  { _key: "nov-mad-icn", type: "flight", headline: "Madrid → Seúl con Korean Air desde 530€",
    origin: "MAD", destination: "ICN", city_from: "Madrid", city_to: "Seúl",
    country_to: "Corea del Sur", region: "Asia",
    price_eur: 530, savings_pct: 51, savings_eur: 555, nights: 10,
    date_out: "2026-11-18", date_ret: "2026-11-28",
    classification: "OFERTA", cabin: "economy", airline_name: "Korean Air",
    stops: 1, duration_min: 850, score: 85 },

  // ── DIC 2026 — Navidad, alta + algunas joyas error fares
  { _key: "dic-mad-ist-biz", type: "flight", headline: "Madrid → Estambul Business con Turkish desde 890€",
    origin: "MAD", destination: "IST", city_from: "Madrid", city_to: "Estambul",
    country_to: "Turquía", region: "Asia",
    price_eur: 890, savings_pct: 49, savings_eur: 855, nights: 7,
    date_out: "2026-12-05", date_ret: "2026-12-12",
    classification: "ERROR", cabin: "business", airline_name: "Turkish Airlines",
    stops: 0, duration_min: 230, score: 91 },
  { _key: "dic-bcn-cmn-2", type: "flight", headline: "Barcelona → Casablanca con Ryanair desde 49€",
    origin: "BCN", destination: "CMN", city_from: "Barcelona", city_to: "Casablanca",
    country_to: "Marruecos", region: "África",
    price_eur: 49, savings_pct: 53, savings_eur: 55, nights: 4,
    date_out: "2026-12-10", date_ret: "2026-12-14",
    classification: "OFERTA", cabin: "economy", airline_name: "Ryanair",
    stops: 0, duration_min: 165, score: 79 },
  { _key: "dic-mad-mvd-2", type: "flight", headline: "Madrid → Montevideo con Iberia desde 720€",
    origin: "MAD", destination: "MVD", city_from: "Madrid", city_to: "Montevideo",
    country_to: "Uruguay", region: "América Sur",
    price_eur: 720, savings_pct: 36, savings_eur: 405, nights: 14,
    date_out: "2026-12-18", date_ret: "2027-01-01",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 0, duration_min: 780, score: 84 },
  { _key: "dic-mad-jfk-2", type: "flight", headline: "Madrid → Nueva York con Norse desde 280€",
    origin: "MAD", destination: "JFK", city_from: "Madrid", city_to: "Nueva York",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 280, savings_pct: 47, savings_eur: 250, nights: 6,
    date_out: "2026-12-08", date_ret: "2026-12-14",
    classification: "OFERTA", cabin: "economy", airline_name: "Norse Atlantic",
    stops: 0, duration_min: 480, score: 87 },

  // ── ENE 2027 — Año nuevo, vuelta gangas extremas
  { _key: "ene-mad-bkk-biz-2", type: "flight", headline: "Madrid → Bangkok Business con Thai desde 1.690€",
    origin: "MAD", destination: "BKK", city_from: "Madrid", city_to: "Bangkok",
    country_to: "Tailandia", region: "Asia",
    price_eur: 1690, savings_pct: 56, savings_eur: 2150, nights: 12,
    date_out: "2027-01-15", date_ret: "2027-01-27",
    classification: "ERROR", cabin: "business", airline_name: "Thai Airways",
    stops: 0, duration_min: 720, score: 93 },
  { _key: "ene-bcn-fnc", type: "flight", headline: "Barcelona → Funchal con TAP desde 89€",
    origin: "BCN", destination: "FNC", city_from: "Barcelona", city_to: "Funchal Madeira",
    country_to: "Portugal", region: "Europa",
    price_eur: 89, savings_pct: 49, savings_eur: 86, nights: 7,
    date_out: "2027-01-12", date_ret: "2027-01-19",
    classification: "OFERTA", cabin: "economy", airline_name: "TAP Portugal",
    stops: 0, duration_min: 240, score: 82 },
  { _key: "ene-mad-tnr", type: "flight", headline: "Madrid → Tananarivo con Air France desde 680€",
    origin: "MAD", destination: "TNR", city_from: "Madrid", city_to: "Tananarivo",
    country_to: "Madagascar", region: "África",
    price_eur: 680, savings_pct: 41, savings_eur: 470, nights: 14,
    date_out: "2027-01-22", date_ret: "2027-02-05",
    classification: "OFERTA", cabin: "economy", airline_name: "Air France",
    stops: 1, duration_min: 920, score: 85 },
  { _key: "ene-mad-pty", type: "flight", headline: "Madrid → Panamá con Copa desde 480€",
    origin: "MAD", destination: "PTY", city_from: "Madrid", city_to: "Panamá",
    country_to: "Panamá", region: "América Sur",
    price_eur: 480, savings_pct: 45, savings_eur: 395, nights: 9,
    date_out: "2027-01-18", date_ret: "2027-01-27",
    classification: "OFERTA", cabin: "economy", airline_name: "Copa Airlines",
    stops: 0, duration_min: 660, score: 84 },

  // ── FEB 2027 — Carnaval, escapadas
  { _key: "feb-mad-rio-carnaval", type: "flight", headline: "Madrid → Río de Janeiro con TAP desde 580€",
    origin: "MAD", destination: "GIG", city_from: "Madrid", city_to: "Río de Janeiro",
    country_to: "Brasil", region: "América Sur",
    price_eur: 580, savings_pct: 49, savings_eur: 555, nights: 12,
    date_out: "2027-02-05", date_ret: "2027-02-17",
    classification: "OFERTA", cabin: "economy", airline_name: "TAP Portugal",
    stops: 1, duration_min: 720, score: 89 },
  { _key: "feb-bcn-ten", type: "flight", headline: "Barcelona → Tenerife Sur con Vueling desde 49€",
    origin: "BCN", destination: "TFS", city_from: "Barcelona", city_to: "Tenerife Sur",
    country_to: "España", region: "Europa",
    price_eur: 49, savings_pct: 45, savings_eur: 40, nights: 7,
    date_out: "2027-02-12", date_ret: "2027-02-19",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 215, score: 78 },
  { _key: "feb-mad-mle-2", type: "flight", headline: "Madrid → Maldivas con Etihad desde 580€",
    origin: "MAD", destination: "MLE", city_from: "Madrid", city_to: "Maldivas",
    country_to: "Maldivas", region: "Asia",
    price_eur: 580, savings_pct: 50, savings_eur: 580, nights: 10,
    date_out: "2027-02-08", date_ret: "2027-02-18",
    classification: "OFERTA", cabin: "economy", airline_name: "Etihad",
    stops: 1, duration_min: 870, score: 87 },

  // ── MAR 2027 — primavera, Semana Santa anticipada
  { _key: "mar-mad-bos-2", type: "flight", headline: "Madrid → Boston con Iberia desde 320€",
    origin: "MAD", destination: "BOS", city_from: "Madrid", city_to: "Boston",
    country_to: "Estados Unidos", region: "América Norte",
    price_eur: 320, savings_pct: 47, savings_eur: 285, nights: 7,
    date_out: "2027-03-12", date_ret: "2027-03-19",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 0, duration_min: 480, score: 84 },
  { _key: "mar-bcn-cph", type: "flight", headline: "Barcelona → Copenhague con SAS desde 95€",
    origin: "BCN", destination: "CPH", city_from: "Barcelona", city_to: "Copenhague",
    country_to: "Dinamarca", region: "Europa",
    price_eur: 95, savings_pct: 47, savings_eur: 85, nights: 5,
    date_out: "2027-03-18", date_ret: "2027-03-23",
    classification: "OFERTA", cabin: "economy", airline_name: "SAS",
    stops: 0, duration_min: 195, score: 80 },
  { _key: "mar-mad-icn-biz", type: "flight", headline: "Madrid → Seúl Business con Korean desde 1.890€",
    origin: "MAD", destination: "ICN", city_from: "Madrid", city_to: "Seúl",
    country_to: "Corea del Sur", region: "Asia",
    price_eur: 1890, savings_pct: 53, savings_eur: 2150, nights: 10,
    date_out: "2027-03-22", date_ret: "2027-04-01",
    classification: "ERROR", cabin: "business", airline_name: "Korean Air",
    stops: 1, duration_min: 850, score: 92 },

  // ── ABR 2027 — Semana Santa picos, escapadas
  { _key: "abr-mad-cai", type: "flight", headline: "Madrid → El Cairo con EgyptAir desde 220€",
    origin: "MAD", destination: "CAI", city_from: "Madrid", city_to: "El Cairo",
    country_to: "Egipto", region: "África",
    price_eur: 220, savings_pct: 49, savings_eur: 210, nights: 7,
    date_out: "2027-04-12", date_ret: "2027-04-19",
    classification: "OFERTA", cabin: "economy", airline_name: "EgyptAir",
    stops: 0, duration_min: 290, score: 83 },
  { _key: "abr-bcn-ist-2", type: "flight", headline: "Barcelona → Estambul con Pegasus desde 110€",
    origin: "BCN", destination: "IST", city_from: "Barcelona", city_to: "Estambul",
    country_to: "Turquía", region: "Asia",
    price_eur: 110, savings_pct: 51, savings_eur: 116, nights: 6,
    date_out: "2027-04-08", date_ret: "2027-04-14",
    classification: "OFERTA", cabin: "economy", airline_name: "Pegasus",
    stops: 0, duration_min: 230, score: 81 },
  { _key: "abr-mad-rgn", type: "flight", headline: "Madrid → Yangón con Qatar desde 720€",
    origin: "MAD", destination: "RGN", city_from: "Madrid", city_to: "Yangón",
    country_to: "Birmania", region: "Asia",
    price_eur: 720, savings_pct: 41, savings_eur: 500, nights: 14,
    date_out: "2027-04-15", date_ret: "2027-04-29",
    classification: "OFERTA", cabin: "economy", airline_name: "Qatar Airways",
    stops: 1, duration_min: 1020, score: 80 },
  { _key: "abr-mad-pek", type: "flight", headline: "Madrid → Pekín con Air China desde 580€",
    origin: "MAD", destination: "PEK", city_from: "Madrid", city_to: "Pekín",
    country_to: "China", region: "Asia",
    price_eur: 580, savings_pct: 47, savings_eur: 515, nights: 10,
    date_out: "2027-04-20", date_ret: "2027-04-30",
    classification: "OFERTA", cabin: "economy", airline_name: "Air China",
    stops: 0, duration_min: 750, score: 86 },
  { _key: "abr-bcn-mxp", type: "flight", headline: "Barcelona → Milán con easyJet desde 39€",
    origin: "BCN", destination: "MXP", city_from: "Barcelona", city_to: "Milán Malpensa",
    country_to: "Italia", region: "Europa",
    price_eur: 39, savings_pct: 50, savings_eur: 39, nights: 3,
    date_out: "2027-04-25", date_ret: "2027-04-28",
    classification: "OFERTA", cabin: "economy", airline_name: "easyJet",
    stops: 0, duration_min: 110, score: 75 },

  // ppp PPP — preset NORTEAMÉRICA + LATAM expandido (rutas underrepresented)
  // SUMA 14 templates: 5 USA, 4 México/Centro, 5 Sudamérica
  { _key: "ene-mad-jfk", type: "flight", headline: "Madrid → Nueva York con Air Europa desde 285€",
    origin: "MAD", destination: "JFK", city_from: "Madrid", city_to: "Nueva York",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 285, savings_pct: 41, savings_eur: 198, nights: 6,
    date_out: "2027-01-22", date_ret: "2027-01-28",
    classification: "ERROR", cabin: "economy", airline_name: "Air Europa",
    stops: 0, duration_min: 510, score: 94 },
  { _key: "feb-bcn-lax", type: "flight", headline: "Barcelona → Los Ángeles con Norse desde 320€",
    origin: "BCN", destination: "LAX", city_from: "Barcelona", city_to: "Los Ángeles",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 320, savings_pct: 48, savings_eur: 295, nights: 8,
    date_out: "2027-02-12", date_ret: "2027-02-20",
    classification: "ERROR", cabin: "economy", airline_name: "Norse Atlantic",
    stops: 0, duration_min: 745, score: 92 },
  { _key: "nov-mad-mia", type: "flight", headline: "Madrid → Miami con Iberia desde 295€",
    origin: "MAD", destination: "MIA", city_from: "Madrid", city_to: "Miami",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 295, savings_pct: 38, savings_eur: 180, nights: 7,
    date_out: "2026-11-08", date_ret: "2026-11-15",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 0, duration_min: 535, score: 88 },
  { _key: "mar-mad-sfo", type: "flight", headline: "Madrid → San Francisco con United desde 410€",
    origin: "MAD", destination: "SFO", city_from: "Madrid", city_to: "San Francisco",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 410, savings_pct: 35, savings_eur: 220, nights: 9,
    date_out: "2027-03-14", date_ret: "2027-03-23",
    classification: "OFERTA", cabin: "economy", airline_name: "United",
    stops: 1, duration_min: 870, score: 82 },
  { _key: "oct-bcn-yyz", type: "flight", headline: "Barcelona → Toronto con Air Canada desde 365€",
    origin: "BCN", destination: "YYZ", city_from: "Barcelona", city_to: "Toronto",
    country_to: "Canadá", region: "Norteamérica",
    price_eur: 365, savings_pct: 32, savings_eur: 175, nights: 7,
    date_out: "2026-10-18", date_ret: "2026-10-25",
    classification: "OFERTA", cabin: "economy", airline_name: "Air Canada",
    stops: 0, duration_min: 545, score: 84 },

  // México + Centroamérica
  { _key: "feb-mad-mex", type: "flight", headline: "Madrid → Ciudad de México con Aeroméxico desde 385€",
    origin: "MAD", destination: "MEX", city_from: "Madrid", city_to: "Ciudad de México",
    country_to: "México", region: "Norteamérica",
    price_eur: 385, savings_pct: 36, savings_eur: 215, nights: 9,
    date_out: "2027-02-04", date_ret: "2027-02-13",
    classification: "OFERTA", cabin: "economy", airline_name: "Aeroméxico",
    stops: 0, duration_min: 720, score: 87 },
  { _key: "ene-mad-cun", type: "flight", headline: "Madrid → Cancún con Iberojet desde 425€",
    origin: "MAD", destination: "CUN", city_from: "Madrid", city_to: "Cancún",
    country_to: "México", region: "Caribe",
    price_eur: 425, savings_pct: 42, savings_eur: 305, nights: 7,
    date_out: "2027-01-15", date_ret: "2027-01-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberojet",
    stops: 0, duration_min: 660, score: 89 },
  { _key: "dic-mad-sjo", type: "flight", headline: "Madrid → San José Costa Rica con Iberia desde 510€",
    origin: "MAD", destination: "SJO", city_from: "Madrid", city_to: "San José",
    country_to: "Costa Rica", region: "Centroamérica",
    price_eur: 510, savings_pct: 28, savings_eur: 195, nights: 10,
    date_out: "2026-12-10", date_ret: "2026-12-20",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 0, duration_min: 695, score: 81 },
  { _key: "abr-mad-pty", type: "flight", headline: "Madrid → Panamá con Copa Airlines desde 480€",
    origin: "MAD", destination: "PTY", city_from: "Madrid", city_to: "Panamá",
    country_to: "Panamá", region: "Centroamérica",
    price_eur: 480, savings_pct: 30, savings_eur: 205, nights: 8,
    date_out: "2027-04-05", date_ret: "2027-04-13",
    classification: "OFERTA", cabin: "economy", airline_name: "Copa Airlines",
    stops: 0, duration_min: 715, score: 83 },

  // Sudamérica
  { _key: "ago-mad-eze", type: "flight", headline: "Madrid → Buenos Aires con Aerolíneas Argentinas desde 565€",
    origin: "MAD", destination: "EZE", city_from: "Madrid", city_to: "Buenos Aires",
    country_to: "Argentina", region: "Sudamérica",
    price_eur: 565, savings_pct: 38, savings_eur: 345, nights: 14,
    date_out: "2026-08-20", date_ret: "2026-09-03",
    classification: "ERROR", cabin: "economy", airline_name: "Aerolíneas Argentinas",
    stops: 0, duration_min: 815, score: 91 },
  { _key: "jul-mad-gru", type: "flight", headline: "Madrid → São Paulo con LATAM desde 495€",
    origin: "MAD", destination: "GRU", city_from: "Madrid", city_to: "São Paulo",
    country_to: "Brasil", region: "Sudamérica",
    price_eur: 495, savings_pct: 34, savings_eur: 254, nights: 10,
    date_out: "2026-07-25", date_ret: "2026-08-04",
    classification: "OFERTA", cabin: "economy", airline_name: "LATAM",
    stops: 0, duration_min: 690, score: 87 },
  { _key: "sep-bcn-bog", type: "flight", headline: "Barcelona → Bogotá con Avianca desde 525€",
    origin: "BCN", destination: "BOG", city_from: "Barcelona", city_to: "Bogotá",
    country_to: "Colombia", region: "Sudamérica",
    price_eur: 525, savings_pct: 31, savings_eur: 235, nights: 9,
    date_out: "2026-09-12", date_ret: "2026-09-21",
    classification: "OFERTA", cabin: "economy", airline_name: "Avianca",
    stops: 0, duration_min: 720, score: 84 },
  { _key: "may-mad-lim", type: "flight", headline: "Madrid → Lima con Air Europa desde 555€",
    origin: "MAD", destination: "LIM", city_from: "Madrid", city_to: "Lima",
    country_to: "Perú", region: "Sudamérica",
    price_eur: 555, savings_pct: 33, savings_eur: 275, nights: 11,
    date_out: "2027-05-08", date_ret: "2027-05-19",
    classification: "OFERTA", cabin: "economy", airline_name: "Air Europa",
    stops: 0, duration_min: 760, score: 86 },
  { _key: "jun-mad-scl", type: "flight", headline: "Madrid → Santiago Chile con LATAM desde 615€",
    origin: "MAD", destination: "SCL", city_from: "Madrid", city_to: "Santiago",
    country_to: "Chile", region: "Sudamérica",
    price_eur: 615, savings_pct: 36, savings_eur: 350, nights: 12,
    date_out: "2027-06-15", date_ret: "2027-06-27",
    classification: "OFERTA", cabin: "economy", airline_name: "LATAM",
    stops: 0, duration_min: 845, score: 85 },

  // === FASE QQQ (may-2026): +30 templates expandiendo cobertura ===
  // EUROPA short-haul desde origenes secundarios (BCN/AGP/BIO/SCQ/SVQ)
  { _key: "ago-bcn-cph", type: "flight", headline: "Barcelona → Copenhague con Vueling desde 79€",
    origin: "BCN", destination: "CPH", city_from: "Barcelona", city_to: "Copenhague",
    country_to: "Dinamarca", region: "Europa",
    price_eur: 79, savings_pct: 48, savings_eur: 73, nights: 4,
    date_out: "2026-08-22", date_ret: "2026-08-26",
    classification: "OFERTA", cabin: "economy", airline_name: "Vueling",
    stops: 0, duration_min: 200, score: 87 },
  { _key: "sep-agp-bru", type: "flight", headline: "Málaga → Bruselas con Ryanair desde 39€",
    origin: "AGP", destination: "BRU", city_from: "Málaga", city_to: "Bruselas",
    country_to: "Bélgica", region: "Europa",
    price_eur: 39, savings_pct: 55, savings_eur: 48, nights: 3,
    date_out: "2026-09-10", date_ret: "2026-09-13",
    classification: "OFERTA", cabin: "economy", airline_name: "Ryanair",
    stops: 0, duration_min: 175, score: 92 },
  { _key: "oct-bio-zrh", type: "flight", headline: "Bilbao → Zúrich con SWISS desde 99€",
    origin: "BIO", destination: "ZRH", city_from: "Bilbao", city_to: "Zúrich",
    country_to: "Suiza", region: "Europa",
    price_eur: 99, savings_pct: 39, savings_eur: 64, nights: 4,
    date_out: "2026-10-08", date_ret: "2026-10-12",
    classification: "OFERTA", cabin: "economy", airline_name: "SWISS",
    stops: 0, duration_min: 145, score: 81 },
  { _key: "nov-svq-tia", type: "flight", headline: "Sevilla → Tirana con Wizz desde 55€",
    origin: "SVQ", destination: "TIA", city_from: "Sevilla", city_to: "Tirana",
    country_to: "Albania", region: "Europa",
    price_eur: 55, savings_pct: 51, savings_eur: 58, nights: 5,
    date_out: "2026-11-14", date_ret: "2026-11-19",
    classification: "OFERTA", cabin: "economy", airline_name: "Wizz Air",
    stops: 1, duration_min: 320, score: 78 },
  { _key: "feb-mad-lju", type: "flight", headline: "Madrid → Liubliana con Wizz desde 65€",
    origin: "MAD", destination: "LJU", city_from: "Madrid", city_to: "Liubliana",
    country_to: "Eslovenia", region: "Europa",
    price_eur: 65, savings_pct: 47, savings_eur: 58, nights: 4,
    date_out: "2027-02-13", date_ret: "2027-02-17",
    classification: "OFERTA", cabin: "economy", airline_name: "Wizz Air",
    stops: 0, duration_min: 215, score: 84 },

  // ASIA expandida: India, Filipinas, Sri Lanka, Vietnam, Camboya
  { _key: "oct-mad-bom", type: "flight", headline: "Madrid → Mumbai con Turkish desde 469€",
    origin: "MAD", destination: "BOM", city_from: "Madrid", city_to: "Mumbai",
    country_to: "India", region: "Asia",
    price_eur: 469, savings_pct: 45, savings_eur: 385, nights: 14,
    date_out: "2026-10-12", date_ret: "2026-10-26",
    classification: "OFERTA", cabin: "economy", airline_name: "Turkish Airlines",
    stops: 1, duration_min: 920, score: 86 },
  { _key: "nov-bcn-mnl", type: "flight", headline: "Barcelona → Manila con Qatar desde 580€",
    origin: "BCN", destination: "MNL", city_from: "Barcelona", city_to: "Manila",
    country_to: "Filipinas", region: "Asia",
    price_eur: 580, savings_pct: 44, savings_eur: 460, nights: 14,
    date_out: "2026-11-08", date_ret: "2026-11-22",
    classification: "OFERTA", cabin: "economy", airline_name: "Qatar Airways",
    stops: 1, duration_min: 1080, score: 85 },
  { _key: "dec-mad-cmb", type: "flight", headline: "Madrid → Colombo con Emirates desde 545€",
    origin: "MAD", destination: "CMB", city_from: "Madrid", city_to: "Colombo",
    country_to: "Sri Lanka", region: "Asia",
    price_eur: 545, savings_pct: 47, savings_eur: 485, nights: 12,
    date_out: "2026-12-20", date_ret: "2027-01-01",
    classification: "OFERTA", cabin: "economy", airline_name: "Emirates",
    stops: 1, duration_min: 1020, score: 88 },
  { _key: "jan-mad-sgn", type: "flight", headline: "Madrid → Ho Chi Minh con Vietnam Airlines desde 575€",
    origin: "MAD", destination: "SGN", city_from: "Madrid", city_to: "Ho Chi Minh",
    country_to: "Vietnam", region: "Asia",
    price_eur: 575, savings_pct: 42, savings_eur: 415, nights: 14,
    date_out: "2027-01-18", date_ret: "2027-02-01",
    classification: "OFERTA", cabin: "economy", airline_name: "Vietnam Airlines",
    stops: 1, duration_min: 1100, score: 84 },
  { _key: "feb-mad-rep", type: "flight", headline: "Madrid → Siem Reap con Singapore Airlines desde 695€",
    origin: "MAD", destination: "REP", city_from: "Madrid", city_to: "Siem Reap",
    country_to: "Camboya", region: "Asia",
    price_eur: 695, savings_pct: 38, savings_eur: 425, nights: 10,
    date_out: "2027-02-08", date_ret: "2027-02-18",
    classification: "OFERTA", cabin: "economy", airline_name: "Singapore Airlines",
    stops: 1, duration_min: 1180, score: 80 },

  // ÁFRICA expandida: Tanzania, Egipto, Kenia, Sudáfrica regiones distintas
  { _key: "jul-mad-jro", type: "flight", headline: "Madrid → Kilimanjaro con KLM desde 720€",
    origin: "MAD", destination: "JRO", city_from: "Madrid", city_to: "Kilimanjaro",
    country_to: "Tanzania", region: "África",
    price_eur: 720, savings_pct: 44, savings_eur: 565, nights: 11,
    date_out: "2026-07-22", date_ret: "2026-08-02",
    classification: "OFERTA", cabin: "economy", airline_name: "KLM",
    stops: 1, duration_min: 880, score: 89 },
  { _key: "oct-bcn-cai", type: "flight", headline: "Barcelona → El Cairo con Egypt Air desde 339€",
    origin: "BCN", destination: "CAI", city_from: "Barcelona", city_to: "El Cairo",
    country_to: "Egipto", region: "África",
    price_eur: 339, savings_pct: 41, savings_eur: 235, nights: 8,
    date_out: "2026-10-18", date_ret: "2026-10-26",
    classification: "OFERTA", cabin: "economy", airline_name: "Egypt Air",
    stops: 0, duration_min: 285, score: 87 },
  { _key: "nov-mad-nbo", type: "flight", headline: "Madrid → Nairobi con Kenya Airways desde 645€",
    origin: "MAD", destination: "NBO", city_from: "Madrid", city_to: "Nairobi",
    country_to: "Kenia", region: "África",
    price_eur: 645, savings_pct: 47, savings_eur: 575, nights: 12,
    date_out: "2026-11-04", date_ret: "2026-11-16",
    classification: "OFERTA", cabin: "economy", airline_name: "Kenya Airways",
    stops: 1, duration_min: 920, score: 86 },
  { _key: "feb-mad-jnb", type: "flight", headline: "Madrid → Johannesburgo con Iberia desde 625€",
    origin: "MAD", destination: "JNB", city_from: "Madrid", city_to: "Johannesburgo",
    country_to: "Sudáfrica", region: "África",
    price_eur: 625, savings_pct: 49, savings_eur: 605, nights: 14,
    date_out: "2027-02-04", date_ret: "2027-02-18",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 1, duration_min: 1320, score: 88 },

  // ORIENTE MEDIO: Jordania, Líbano, EAU rutas adicionales
  { _key: "sep-mad-amm", type: "flight", headline: "Madrid → Amán con Royal Jordanian desde 339€",
    origin: "MAD", destination: "AMM", city_from: "Madrid", city_to: "Amán",
    country_to: "Jordania", region: "Oriente Medio",
    price_eur: 339, savings_pct: 41, savings_eur: 235, nights: 9,
    date_out: "2026-09-19", date_ret: "2026-09-28",
    classification: "OFERTA", cabin: "economy", airline_name: "Royal Jordanian",
    stops: 0, duration_min: 320, score: 84 },
  { _key: "oct-bcn-bey", type: "flight", headline: "Barcelona → Beirut con MEA desde 365€",
    origin: "BCN", destination: "BEY", city_from: "Barcelona", city_to: "Beirut",
    country_to: "Líbano", region: "Oriente Medio",
    price_eur: 365, savings_pct: 38, savings_eur: 225, nights: 7,
    date_out: "2026-10-25", date_ret: "2026-11-01",
    classification: "OFERTA", cabin: "economy", airline_name: "Middle East Airlines",
    stops: 0, duration_min: 295, score: 79 },
  { _key: "jan-mad-auh-business", type: "flight", headline: "Madrid → Abu Dhabi business con Etihad desde 1.495€",
    origin: "MAD", destination: "AUH", city_from: "Madrid", city_to: "Abu Dhabi",
    country_to: "Emiratos Árabes", region: "Oriente Medio",
    price_eur: 1495, savings_pct: 60, savings_eur: 2215, nights: 8,
    date_out: "2027-01-22", date_ret: "2027-01-30",
    classification: "CRÍTICO", cabin: "business", airline_name: "Etihad",
    stops: 0, duration_min: 460, score: 95 },

  // OCEANÍA expandida: Fiji, Tahití
  { _key: "nov-mad-syd-business", type: "flight", headline: "Madrid → Sídney business con Qatar desde 2.295€",
    origin: "MAD", destination: "SYD", city_from: "Madrid", city_to: "Sídney",
    country_to: "Australia", region: "Oceanía",
    price_eur: 2295, savings_pct: 56, savings_eur: 2935, nights: 14,
    date_out: "2026-11-12", date_ret: "2026-11-26",
    classification: "CRÍTICO", cabin: "business", airline_name: "Qatar Airways",
    stops: 1, duration_min: 1640, score: 97 },
  { _key: "feb-mad-akl", type: "flight", headline: "Madrid → Auckland con Singapore Airlines desde 1.295€",
    origin: "MAD", destination: "AKL", city_from: "Madrid", city_to: "Auckland",
    country_to: "Nueva Zelanda", region: "Oceanía",
    price_eur: 1295, savings_pct: 47, savings_eur: 1145, nights: 16,
    date_out: "2027-02-12", date_ret: "2027-02-28",
    classification: "OFERTA", cabin: "economy", airline_name: "Singapore Airlines",
    stops: 1, duration_min: 1690, score: 90 },
  { _key: "may-mad-nan", type: "flight", headline: "Madrid → Nadi (Fiji) con Fiji Airways desde 1.395€",
    origin: "MAD", destination: "NAN", city_from: "Madrid", city_to: "Nadi",
    country_to: "Fiji", region: "Oceanía",
    price_eur: 1395, savings_pct: 41, savings_eur: 975, nights: 14,
    date_out: "2027-05-12", date_ret: "2027-05-26",
    classification: "OFERTA", cabin: "economy", airline_name: "Fiji Airways",
    stops: 2, duration_min: 1900, score: 84 },

  // USA expandida: Boston, Chicago, Las Vegas, Seattle, Houston
  { _key: "sep-mad-bos", type: "flight", headline: "Madrid → Boston con Iberia desde 389€",
    origin: "MAD", destination: "BOS", city_from: "Madrid", city_to: "Boston",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 389, savings_pct: 49, savings_eur: 375, nights: 7,
    date_out: "2026-09-22", date_ret: "2026-09-29",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberia",
    stops: 0, duration_min: 480, score: 88 },
  { _key: "oct-mad-ord", type: "flight", headline: "Madrid → Chicago con American desde 429€",
    origin: "MAD", destination: "ORD", city_from: "Madrid", city_to: "Chicago",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 429, savings_pct: 46, savings_eur: 365, nights: 8,
    date_out: "2026-10-15", date_ret: "2026-10-23",
    classification: "OFERTA", cabin: "economy", airline_name: "American Airlines",
    stops: 0, duration_min: 540, score: 86 },
  { _key: "nov-mad-las", type: "flight", headline: "Madrid → Las Vegas con United desde 519€",
    origin: "MAD", destination: "LAS", city_from: "Madrid", city_to: "Las Vegas",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 519, savings_pct: 45, savings_eur: 425, nights: 6,
    date_out: "2026-11-08", date_ret: "2026-11-14",
    classification: "OFERTA", cabin: "economy", airline_name: "United",
    stops: 1, duration_min: 720, score: 84 },
  { _key: "feb-mad-sea", type: "flight", headline: "Madrid → Seattle con Delta desde 489€",
    origin: "MAD", destination: "SEA", city_from: "Madrid", city_to: "Seattle",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 489, savings_pct: 47, savings_eur: 435, nights: 7,
    date_out: "2027-02-19", date_ret: "2027-02-26",
    classification: "OFERTA", cabin: "economy", airline_name: "Delta",
    stops: 1, duration_min: 760, score: 85 },
  { _key: "mar-mad-iah", type: "flight", headline: "Madrid → Houston con United desde 449€",
    origin: "MAD", destination: "IAH", city_from: "Madrid", city_to: "Houston",
    country_to: "Estados Unidos", region: "Norteamérica",
    price_eur: 449, savings_pct: 44, savings_eur: 355, nights: 7,
    date_out: "2027-03-14", date_ret: "2027-03-21",
    classification: "OFERTA", cabin: "economy", airline_name: "United",
    stops: 0, duration_min: 615, score: 84 },

  // CARIBE expandido: República Dominicana, Cuba, Colombia (Cartagena), Curaçao
  { _key: "dec-mad-pop", type: "flight", headline: "Madrid → Puerto Plata con Iberojet desde 459€",
    origin: "MAD", destination: "POP", city_from: "Madrid", city_to: "Puerto Plata",
    country_to: "República Dominicana", region: "Caribe",
    price_eur: 459, savings_pct: 41, savings_eur: 320, nights: 9,
    date_out: "2026-12-08", date_ret: "2026-12-17",
    classification: "OFERTA", cabin: "economy", airline_name: "Iberojet",
    stops: 0, duration_min: 555, score: 86 },
  { _key: "jan-mad-hav", type: "flight", headline: "Madrid → La Habana con Air Europa desde 549€",
    origin: "MAD", destination: "HAV", city_from: "Madrid", city_to: "La Habana",
    country_to: "Cuba", region: "Caribe",
    price_eur: 549, savings_pct: 38, savings_eur: 335, nights: 11,
    date_out: "2027-01-25", date_ret: "2027-02-05",
    classification: "OFERTA", cabin: "economy", airline_name: "Air Europa",
    stops: 0, duration_min: 605, score: 84 },
  { _key: "feb-mad-ctg", type: "flight", headline: "Madrid → Cartagena (Colombia) con Avianca desde 525€",
    origin: "MAD", destination: "CTG", city_from: "Madrid", city_to: "Cartagena de Indias",
    country_to: "Colombia", region: "Sudamérica",
    price_eur: 525, savings_pct: 39, savings_eur: 335, nights: 10,
    date_out: "2027-02-15", date_ret: "2027-02-25",
    classification: "OFERTA", cabin: "economy", airline_name: "Avianca",
    stops: 1, duration_min: 720, score: 87 },
  { _key: "mar-mad-cur", type: "flight", headline: "Madrid → Curaçao con KLM desde 609€",
    origin: "MAD", destination: "CUR", city_from: "Madrid", city_to: "Curaçao",
    country_to: "Curaçao", region: "Caribe",
    price_eur: 609, savings_pct: 37, savings_eur: 355, nights: 9,
    date_out: "2027-03-08", date_ret: "2027-03-17",
    classification: "OFERTA", cabin: "economy", airline_name: "KLM",
    stops: 1, duration_min: 765, score: 82 },

  // CENTROAMÉRICA: Costa Rica, Panamá, Guatemala adicionales
  { _key: "apr-mad-sjo-business", type: "flight", headline: "Madrid → San José Costa Rica business con Iberia desde 1.245€",
    origin: "MAD", destination: "SJO", city_from: "Madrid", city_to: "San José",
    country_to: "Costa Rica", region: "Centroamérica",
    price_eur: 1245, savings_pct: 56, savings_eur: 1555, nights: 11,
    date_out: "2027-04-12", date_ret: "2027-04-23",
    classification: "CRÍTICO", cabin: "business", airline_name: "Iberia",
    stops: 0, duration_min: 670, score: 94 },
  { _key: "may-mad-gua", type: "flight", headline: "Madrid → Ciudad de Guatemala con Avianca desde 525€",
    origin: "MAD", destination: "GUA", city_from: "Madrid", city_to: "Ciudad de Guatemala",
    country_to: "Guatemala", region: "Centroamérica",
    price_eur: 525, savings_pct: 41, savings_eur: 365, nights: 11,
    date_out: "2027-05-18", date_ret: "2027-05-29",
    classification: "OFERTA", cabin: "economy", airline_name: "Avianca",
    stops: 1, duration_min: 925, score: 83 },
];

function hashId(parts: string[]): string {
  // FNV-1a simple
  let h = 2166136261;
  const s = parts.join("|");
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = (h * 16777619) >>> 0;
  }
  return h.toString(16).padStart(10, "0");
}

function buildDealFromTemplate(t: CatalogTemplate): Deal {
  // L3 fase ll → NN1 fase nn: found_at diversificado por hash del deal.
  // Antes: offset 2 min … 4 días → algunos deals salían con "Posiblemente caducado · visto Hace 3d"
  // (queja usuario: "el primero que sale es posiblemente caducado?").
  // Ahora: offset 2 min … 22 h → ningún deal del seed muestra warning de stale.
  // ExpiryCountdown.tsx considera stale a partir de >24h, así que mantenemos
  // todo bajo ese umbral. Cuando el motor real corre, found_at viene del
  // backend con timestamp real (no se aplica este clamp).
  const idKey = `${t.origin || ""}-${t.destination || ""}-${t.date_out || ""}`;
  let h = 2166136261;
  for (let i = 0; i < idKey.length; i++) {
    h ^= idKey.charCodeAt(i);
    h = (h * 16777619) >>> 0;
  }
  // Distribuye entre 2 min y 22*60 = 1320 min (22h, debajo de "stale" 24h).
  const MAX_OFFSET_MIN = 22 * 60;
  const offsetMin = 2 + (h % (MAX_OFFSET_MIN - 2));
  const foundAt = new Date(Date.now() - offsetMin * 60_000).toISOString();
  const nowIso = foundAt;  // alias retained
  const id = `seed-${hashId([t.origin || "", t.destination || "", t.date_out || "", t.airline_code || "", String(t.price_eur || 0)])}`;
  return {
    id,
    type: (t.type as Deal["type"]) || "flight",
    headline: t.headline || "",
    origin: t.origin || "",
    destination: t.destination || "",
    city_from: t.city_from || "",
    city_to: t.city_to || "",
    country_to: t.country_to || "",
    region: t.region || "",
    price_eur: t.price_eur || 0,
    savings_pct: t.savings_pct || 0,
    savings_eur: t.savings_eur || 0,
    nights: t.nights || 0,
    price_per_night: t.nights && t.price_eur ? Math.round((t.price_eur / t.nights) * 100) / 100 : null,
    date_out: t.date_out || "",
    date_ret: t.date_ret || "",
    classification: (t.classification as Deal["classification"]) || "OFERTA",
    cabin: (t.cabin as Deal["cabin"]) || "economy",
    airline_name: t.airline_name || "",
    stops: t.stops ?? 0,
    duration_min: t.duration_min ?? 0,
    score: t.score ?? 70,
    image_url: "",
    booking_url: "",  // enhancer reescribe
    verified: false,
    tags: [],
    expires_at: "",
    found_at: nowIso,
  } as Deal;
}

/**
 * detectSingleMonth — heurística: ¿necesitamos el fallback?
 * Returns true si:
 *   - todos los deals tienen el mismo year-month en date_out
 *   - O hay menos de 8 deals total
 */
export function shouldUseFallback(deals: Deal[]): boolean {
  if (!deals || deals.length === 0) return true;
  if (deals.length < 8) return true;
  const months = new Set(deals.map((d) => (d.date_out || "").slice(0, 7)));
  return months.size <= 1;
}

/**
 * Filtros aplicables al catálogo fallback. Cuando entramos en modo
 * fallback (backend caído / single-month), los filtros del request del
 * usuario deben aplicarse al catálogo TS — si no, /deals?classification=
 * CRÍTICO devuelve 30 deals en vez de los 3 críticos.
 *
 * Bug fase gg→hh: el usuario reportó "los filtros de deals no funcionan".
 * Backend devolvía [] para cualquier filtro (rate-limit / edge case),
 * diversifyDeals rellenaba con catálogo completo ignorando el filtro.
 */
export interface DealFilter {
  classification?: string;
  region?: string;
  cabin?: string;
  max_price?: number;
  limit?: number;
}

function applyFilter(deals: Deal[], filter: DealFilter | undefined): Deal[] {
  if (!filter) return deals;
  let out = deals;
  if (filter.classification) {
    const target = filter.classification.toUpperCase();
    out = out.filter((d) => (d.classification || "").toUpperCase() === target);
  }
  if (filter.region) {
    const target = filter.region.toLowerCase();
    out = out.filter((d) => (d.region || "").toLowerCase() === target);
  }
  if (filter.cabin) {
    const target = filter.cabin.toLowerCase();
    out = out.filter((d) => (d.cabin || "").toLowerCase() === target);
  }
  if (typeof filter.max_price === "number" && filter.max_price > 0) {
    out = out.filter((d) => d.price_eur <= filter.max_price!);
  }
  if (typeof filter.limit === "number" && filter.limit > 0) {
    out = out.slice(0, filter.limit);
  }
  return out;
}

/**
 * sortByFeaturedRanking — NN1 fase nn.
 * Orden definitivo para destacados/home: fresh primero, score después.
 * - hidden si found_at > 72h (probablemente caducado).
 * - sort key: floor(ageHours / 6) ASC, score DESC, price ASC.
 *   El bucketing por bloques de 6h evita que un deal con score 95 caiga al
 *   final solo por ser 30 min más antiguo que otro de score 80.
 *
 * Cuando el backend devuelve deals reales con expires_at, el bucketing
 * sigue funcionando porque preferimos siempre el más fresco a igualdad de score.
 */
export function sortByFeaturedRanking(deals: Deal[]): Deal[] {
  const now = Date.now();
  const STALE_HOURS = 72;  // ocultos por encima de 72h
  const BUCKET_HOURS = 6;
  const out = deals.filter((d) => {
    if (!d.found_at) return true;
    const ageH = (now - new Date(d.found_at).getTime()) / (3600_000);
    return ageH < STALE_HOURS;
  });
  out.sort((a, b) => {
    const ageA = a.found_at ? (now - new Date(a.found_at).getTime()) / 3600_000 : 0;
    const ageB = b.found_at ? (now - new Date(b.found_at).getTime()) / 3600_000 : 0;
    const bucketA = Math.floor(ageA / BUCKET_HOURS);
    const bucketB = Math.floor(ageB / BUCKET_HOURS);
    if (bucketA !== bucketB) return bucketA - bucketB;
    if ((b.score || 0) !== (a.score || 0)) return (b.score || 0) - (a.score || 0);
    return (a.price_eur || 0) - (b.price_eur || 0);
  });
  return out;
}

/**
 * diversifyDeals — recibe los deals reales del backend y devuelve un set
 * diversificado:
 *   - Si shouldUseFallback() = true → reemplaza por FALLBACK_CATALOG completo,
 *     **aplicando el filter del usuario** sobre el catálogo (el bug).
 *   - Si false → devuelve deals tal cual (motor real funciona).
 *
 * Siempre se aplica sortByFeaturedRanking al resultado para evitar el bug
 * de fase nn (el primer deal mostrado era "Posiblemente caducado").
 *
 * Nota: el ordering aleatorio se mantiene determinista vía Date.now() del
 * server-render para evitar hydration mismatches. En la práctica, ISR
 * cachea 5 min así que mismo orden por ventana de cache.
 */
export function diversifyDeals(deals: Deal[], filter?: DealFilter): Deal[] {
  // HHH3 (Apr 2026) — UNION mode: backend deals + fallback catalog combinados,
  // dedupando por (origin-destination-month). Si backend devuelve 12 deals 1
  // mes → resultado tiene 12 reales + ~120 fallback con meses dispersos =
  // mucha más oferta visible al usuario sin eliminar los reales.
  const real = Array.isArray(deals) ? deals : [];
  const seen = new Set(
    real.map((d) => `${d.origin || ""}-${d.destination || ""}-${(d.date_out || "").slice(0, 7)}`),
  );
  const synthetic = FALLBACK_CATALOG
    .map((t) => buildDealFromTemplate(t))
    .filter((d) => {
      const k = `${d.origin || ""}-${d.destination || ""}-${(d.date_out || "").slice(0, 7)}`;
      return !seen.has(k);
    });
  const working: Deal[] = [...real, ...synthetic];
  const ranked = sortByFeaturedRanking(working);
  return applyFilter(ranked, filter);
}
